/**
 * Semantic Token Tailwind Config
 * DO NOT EDIT DIRECTLY - This file is auto-generated
 * Generated on Thu, 08 Oct 2026 14:54:44 GMT
 */

export const StyleTailwind = {
	background: 'var(--background)',
	foreground: 'var(--foreground)',
	card: 'var(--card)',
	'card-foreground': 'var(--card-foreground)',
	popover: 'var(--popover)',
	'popover-foreground': 'var(--popover-foreground)',
	primary: 'var(--primary)',
	secondary: 'var(--secondary)',
	muted: 'var(--muted)',
	'muted-foreground': 'var(--muted-foreground)',
	accent: 'var(--accent)',
	'accent-foreground': 'var(--accent-foreground)',
	destructive: 'var(--destructive)',
	'destructive-foreground': 'var(--destructive-foreground)',
	border: 'var(--border)',
	input: 'var(--input)',
	ring: 'var(--ring)',
	radius: 'var(--radius)',
	'chart-1': 'var(--chart-1)',
	'chart-2': 'var(--chart-2)',
	'chart-3': 'var(--chart-3)',
	'chart-4': 'var(--chart-4)',
	'chart-5': 'var(--chart-5)',
	sidebar: 'var(--sidebar)',
	'sidebar-foreground': 'var(--sidebar-foreground)',
	'sidebar-primary': 'var(--sidebar-primary)',
	'sidebar-primary-foreground': 'var(--sidebar-primary-foreground)',
	'sidebar-accent': 'var(--sidebar-accent)',
	'sidebar-accent-foreground': 'var(--sidebar-accent-foreground)',
	'sidebar-border': 'var(--sidebar-border)',
	'sidebar-ring': 'var(--sidebar-ring)',
	'font-sans': 'var(--font-sans)',
	'font-serif': 'var(--font-serif)',
	'font-mono': 'var(--font-mono)',
	'base-white': 'var(--base-white)',
	'base-black': 'var(--base-black)',
	'l1-background': 'var(--l1-background)',
	'l2-background': 'var(--l2-background)',
	'l3-background': 'var(--l3-background)',
	'l1-background-hover': 'var(--l1-background-hover)',
	'l2-background-hover': 'var(--l2-background-hover)',
	'l3-background-hover': 'var(--l3-background-hover)',
	'l1-foreground': 'var(--l1-foreground)',
	'l1-foreground-hover': 'var(--l1-foreground-hover)',
	'l2-foreground': 'var(--l2-foreground)',
	'l2-foreground-hover': 'var(--l2-foreground-hover)',
	'l3-foreground': 'var(--l3-foreground)',
	'l3-foreground-hover': 'var(--l3-foreground-hover)',
	'l1-border': 'var(--l1-border)',
	'l2-border': 'var(--l2-border)',
	'l3-border': 'var(--l3-border)',
	'primary-background': 'var(--primary-background)',
	'primary-background-hover': 'var(--primary-background-hover)',
	'primary-foreground': 'var(--primary-foreground)',
	'primary-foreground-hover': 'var(--primary-foreground-hover)',
	'secondary-background': 'var(--secondary-background)',
	'secondary-background-hover': 'var(--secondary-background-hover)',
	'secondary-foreground': 'var(--secondary-foreground)',
	'secondary-foreground-hover': 'var(--secondary-foreground-hover)',
	'secondary-border': 'var(--secondary-border)',
	'success-background': 'var(--success-background)',
	'success-background-hover': 'var(--success-background-hover)',
	'success-foreground': 'var(--success-foreground)',
	'success-foreground-hover': 'var(--success-foreground-hover)',
	'warning-background': 'var(--warning-background)',
	'warning-background-hover': 'var(--warning-background-hover)',
	'warning-foreground': 'var(--warning-foreground)',
	'warning-foreground-hover': 'var(--warning-foreground-hover)',
	'danger-background': 'var(--danger-background)',
	'danger-background-hover': 'var(--danger-background-hover)',
	'danger-foreground': 'var(--danger-foreground)',
	'danger-foreground-hover': 'var(--danger-foreground-hover)',
	'primary-link': 'var(--primary-link)',
	'primary-link-hover': 'var(--primary-link-hover)',
	'secondary-link': 'var(--secondary-link)',
	'secondary-link-hover': 'var(--secondary-link-hover)',
	'success-link': 'var(--success-link)',
	'success-link-hover': 'var(--success-link-hover)',
	'warning-link': 'var(--warning-link)',
	'warning-link-hover': 'var(--warning-link-hover)',
	'danger-link': 'var(--danger-link)',
	'danger-link-hover': 'var(--danger-link-hover)',
	'info-link': 'var(--info-link)',
	'info-link-hover': 'var(--info-link-hover)',
	'archive-link': 'var(--archive-link)',
	'archive-link-hover': 'var(--archive-link-hover)',
	'highlight-danger-link': 'var(--highlight-danger-link)',
	'highlight-danger-link-hover': 'var(--highlight-danger-link-hover)',
	'l1-background-transparent': 'var(--l1-background-transparent)',
	'l1-background-60': 'var(--l1-background-60)',
	'l2-background-transparent': 'var(--l2-background-transparent)',
	'l2-background-60': 'var(--l2-background-60)',
	'l3-background-transparent': 'var(--l3-background-transparent)',
	'l3-background-60': 'var(--l3-background-60)',
	'l3-background-30': 'var(--l3-background-30)',
	'surface-1': 'var(--surface-1)',
	'surface-2': 'var(--surface-2)',
	'surface-3': 'var(--surface-3)',
	'surface-static': 'var(--surface-static)',
	'alert-strip-button-background': 'var(--alert-strip-button-background)',
	'alert-strip-button-background-hover':
		'var(--alert-strip-button-background-hover)',
	'alert-strip-button-foreground': 'var(--alert-strip-button-foreground)',
	'alert-strip-decoration': 'var(--alert-strip-decoration)',
	'alert-strip-primary-background': 'var(--alert-strip-primary-background)',
	'alert-strip-primary-foreground': 'var(--alert-strip-primary-foreground)',
	'alert-strip-primary-link-hover': 'var(--alert-strip-primary-link-hover)',
	'alert-strip-secondary-background': 'var(--alert-strip-secondary-background)',
	'alert-strip-secondary-foreground': 'var(--alert-strip-secondary-foreground)',
	'alert-strip-secondary-link-hover': 'var(--alert-strip-secondary-link-hover)',
	'alert-strip-success-background': 'var(--alert-strip-success-background)',
	'alert-strip-success-foreground': 'var(--alert-strip-success-foreground)',
	'alert-strip-success-link-hover': 'var(--alert-strip-success-link-hover)',
	'alert-strip-danger-background': 'var(--alert-strip-danger-background)',
	'alert-strip-danger-foreground': 'var(--alert-strip-danger-foreground)',
	'alert-strip-danger-link-hover': 'var(--alert-strip-danger-link-hover)',
	'alert-strip-warning-background': 'var(--alert-strip-warning-background)',
	'alert-strip-warning-foreground': 'var(--alert-strip-warning-foreground)',
	'alert-strip-warning-link-hover': 'var(--alert-strip-warning-link-hover)',
	'alert-strip-info-background': 'var(--alert-strip-info-background)',
	'alert-strip-info-foreground': 'var(--alert-strip-info-foreground)',
	'alert-strip-info-link-hover': 'var(--alert-strip-info-link-hover)',
	'alert-strip-archive-background': 'var(--alert-strip-archive-background)',
	'alert-strip-archive-foreground': 'var(--alert-strip-archive-foreground)',
	'alert-strip-archive-link-hover': 'var(--alert-strip-archive-link-hover)',
	'alert-strip-highlight-danger-background':
		'var(--alert-strip-highlight-danger-background)',
	'alert-strip-highlight-danger-foreground':
		'var(--alert-strip-highlight-danger-foreground)',
	'alert-strip-highlight-danger-link-hover':
		'var(--alert-strip-highlight-danger-link-hover)',
	'callout-primary-background': 'var(--callout-primary-background)',
	'callout-primary-border': 'var(--callout-primary-border)',
	'callout-primary-background-hover': 'var(--callout-primary-background-hover)',
	'callout-primary-title': 'var(--callout-primary-title)',
	'callout-primary-description': 'var(--callout-primary-description)',
	'callout-primary-icon': 'var(--callout-primary-icon)',
	'callout-success-background': 'var(--callout-success-background)',
	'callout-success-border': 'var(--callout-success-border)',
	'callout-success-background-hover': 'var(--callout-success-background-hover)',
	'callout-success-title': 'var(--callout-success-title)',
	'callout-success-description': 'var(--callout-success-description)',
	'callout-success-icon': 'var(--callout-success-icon)',
	'callout-warning-background': 'var(--callout-warning-background)',
	'callout-warning-border': 'var(--callout-warning-border)',
	'callout-warning-background-hover': 'var(--callout-warning-background-hover)',
	'callout-warning-title': 'var(--callout-warning-title)',
	'callout-warning-description': 'var(--callout-warning-description)',
	'callout-warning-icon': 'var(--callout-warning-icon)',
	'callout-danger-background': 'var(--callout-danger-background)',
	'callout-danger-border': 'var(--callout-danger-border)',
	'callout-danger-background-hover': 'var(--callout-danger-background-hover)',
	'callout-danger-title': 'var(--callout-danger-title)',
	'callout-danger-description': 'var(--callout-danger-description)',
	'callout-danger-icon': 'var(--callout-danger-icon)',
	'callout-error-background': 'var(--callout-error-background)',
	'callout-error-border': 'var(--callout-error-border)',
	'callout-error-title': 'var(--callout-error-title)',
	'callout-error-description': 'var(--callout-error-description)',
	'callout-error-icon': 'var(--callout-error-icon)',
	'callout-info-background': 'var(--callout-info-background)',
	'callout-info-border': 'var(--callout-info-border)',
	'callout-info-background-hover': 'var(--callout-info-background-hover)',
	'callout-info-title': 'var(--callout-info-title)',
	'callout-info-description': 'var(--callout-info-description)',
	'callout-info-icon': 'var(--callout-info-icon)',
	'callout-archive-background': 'var(--callout-archive-background)',
	'callout-archive-border': 'var(--callout-archive-border)',
	'callout-archive-background-hover': 'var(--callout-archive-background-hover)',
	'callout-archive-title': 'var(--callout-archive-title)',
	'callout-archive-description': 'var(--callout-archive-description)',
	'callout-archive-icon': 'var(--callout-archive-icon)',
	'callout-highlight-danger-background':
		'var(--callout-highlight-danger-background)',
	'callout-highlight-danger-border': 'var(--callout-highlight-danger-border)',
	'callout-highlight-danger-background-hover':
		'var(--callout-highlight-danger-background-hover)',
	'callout-highlight-danger-title': 'var(--callout-highlight-danger-title)',
	'callout-highlight-danger-description':
		'var(--callout-highlight-danger-description)',
	'callout-highlight-danger-icon': 'var(--callout-highlight-danger-icon)',
	'callout-secondary-background': 'var(--callout-secondary-background)',
	'callout-secondary-border': 'var(--callout-secondary-border)',
	'callout-secondary-background-hover':
		'var(--callout-secondary-background-hover)',
	'callout-secondary-title': 'var(--callout-secondary-title)',
	'callout-secondary-description': 'var(--callout-secondary-description)',
	'callout-secondary-icon': 'var(--callout-secondary-icon)',
	'size-icon-callout-sm': 'var(--size-icon-callout-sm)',
	'size-icon-callout-md': 'var(--size-icon-callout-md)',
	'accent-primary': 'var(--accent-primary)',
	'accent-primary-hover': 'var(--accent-primary-hover)',
	'accent-primary-foreground': 'var(--accent-primary-foreground)',
	'accent-forest': 'var(--accent-forest)',
	'accent-forest-hover': 'var(--accent-forest-hover)',
	'accent-forest-foreground': 'var(--accent-forest-foreground)',
	'accent-amber': 'var(--accent-amber)',
	'accent-amber-hover': 'var(--accent-amber-hover)',
	'accent-amber-foreground': 'var(--accent-amber-foreground)',
	'accent-cherry': 'var(--accent-cherry)',
	'accent-cherry-hover': 'var(--accent-cherry-hover)',
	'accent-cherry-foreground': 'var(--accent-cherry-foreground)',
	'accent-aqua': 'var(--accent-aqua)',
	'accent-aqua-hover': 'var(--accent-aqua-hover)',
	'accent-aqua-foreground': 'var(--accent-aqua-foreground)',
	'accent-sakura': 'var(--accent-sakura)',
	'accent-sakura-hover': 'var(--accent-sakura-hover)',
	'accent-sakura-foreground': 'var(--accent-sakura-foreground)',
	'accent-sienna': 'var(--accent-sienna)',
	'accent-sienna-hover': 'var(--accent-sienna-hover)',
	'accent-sienna-foreground': 'var(--accent-sienna-foreground)',
	'ghost-background': 'var(--ghost-background)',
	'ghost-background-hover': 'var(--ghost-background-hover)',
	'ghost-foreground': 'var(--ghost-foreground)',
	'ghost-foreground-hover': 'var(--ghost-foreground-hover)',
	'ghost-border': 'var(--ghost-border)',
	'action-background': 'var(--action-background)',
	'action-background-hover': 'var(--action-background-hover)',
	'action-border': 'var(--action-border)',
	'action-border-hover': 'var(--action-border-hover)',
	'action-foreground': 'var(--action-foreground)',
	'action-foreground-hover': 'var(--action-foreground-hover)',
	'announcement-banner-warning-background':
		'var(--announcement-banner-warning-background)',
	'announcement-banner-warning-border':
		'var(--announcement-banner-warning-border)',
	'announcement-banner-warning-title':
		'var(--announcement-banner-warning-title)',
	'announcement-banner-warning-description':
		'var(--announcement-banner-warning-description)',
	'announcement-banner-primary-background':
		'var(--announcement-banner-primary-background)',
	'announcement-banner-primary-border':
		'var(--announcement-banner-primary-border)',
	'announcement-banner-primary-title':
		'var(--announcement-banner-primary-title)',
	'announcement-banner-primary-description':
		'var(--announcement-banner-primary-description)',
	'announcement-banner-error-background':
		'var(--announcement-banner-error-background)',
	'announcement-banner-error-border': 'var(--announcement-banner-error-border)',
	'announcement-banner-error-title': 'var(--announcement-banner-error-title)',
	'announcement-banner-error-description':
		'var(--announcement-banner-error-description)',
	'announcement-banner-success-background':
		'var(--announcement-banner-success-background)',
	'announcement-banner-success-border':
		'var(--announcement-banner-success-border)',
	'announcement-banner-success-title':
		'var(--announcement-banner-success-title)',
	'announcement-banner-success-description':
		'var(--announcement-banner-success-description)',
	'kbd-active-background': 'var(--kbd-active-background)',
	'control-icon-foreground': 'var(--control-icon-foreground)',
	'control-icon-foreground-contrast': 'var(--control-icon-foreground-contrast)',
	'shadow-sidebar': 'var(--shadow-sidebar)',
	'shadow-dropdown': 'var(--shadow-dropdown)',
	'shadow-drawer': 'var(--shadow-drawer)',
	'shadow-dialog': 'var(--shadow-dialog)',
	'shadow-toast': 'var(--shadow-toast)',
	'shadow-tooltip': 'var(--shadow-tooltip)',
	'pill-primary-background': 'var(--pill-primary-background)',
	'pill-primary-border': 'var(--pill-primary-border)',
	'pill-primary-label': 'var(--pill-primary-label)',
	'pill-primary-label-hover': 'var(--pill-primary-label-hover)',
	'pill-success-background': 'var(--pill-success-background)',
	'pill-success-border': 'var(--pill-success-border)',
	'pill-success-label': 'var(--pill-success-label)',
	'pill-success-label-hover': 'var(--pill-success-label-hover)',
	'pill-warning-background': 'var(--pill-warning-background)',
	'pill-warning-border': 'var(--pill-warning-border)',
	'pill-warning-label': 'var(--pill-warning-label)',
	'pill-warning-label-hover': 'var(--pill-warning-label-hover)',
	'pill-danger-background': 'var(--pill-danger-background)',
	'pill-danger-border': 'var(--pill-danger-border)',
	'pill-danger-label': 'var(--pill-danger-label)',
	'pill-danger-label-hover': 'var(--pill-danger-label-hover)',
	'pill-outlined-background': 'var(--pill-outlined-background)',
	'pill-outlined-background-hover': 'var(--pill-outlined-background-hover)',
	'pill-outlined-border': 'var(--pill-outlined-border)',
	'pill-outlined-label': 'var(--pill-outlined-label)',
	'pill-outlined-label-hover': 'var(--pill-outlined-label-hover)',
	'pill-rect-solid-background': 'var(--pill-rect-solid-background)',
	'pill-rect-solid-background-hover': 'var(--pill-rect-solid-background-hover)',
	'pill-rect-solid-label': 'var(--pill-rect-solid-label)',
	'pill-rect-solid-label-hover': 'var(--pill-rect-solid-label-hover)',
	'pill-rect-solid-dismiss-icon': 'var(--pill-rect-solid-dismiss-icon)',
	'pill-rect-solid-dismiss-icon-hover':
		'var(--pill-rect-solid-dismiss-icon-hover)',
	'pill-info-background': 'var(--pill-info-background)',
	'pill-info-border': 'var(--pill-info-border)',
	'pill-info-label': 'var(--pill-info-label)',
	'pill-info-label-hover': 'var(--pill-info-label-hover)',
	'pill-archive-background': 'var(--pill-archive-background)',
	'pill-archive-border': 'var(--pill-archive-border)',
	'pill-archive-label': 'var(--pill-archive-label)',
	'pill-archive-label-hover': 'var(--pill-archive-label-hover)',
	'pill-highlight-danger-background': 'var(--pill-highlight-danger-background)',
	'pill-highlight-danger-border': 'var(--pill-highlight-danger-border)',
	'pill-highlight-danger-label': 'var(--pill-highlight-danger-label)',
	'pill-highlight-danger-label-hover':
		'var(--pill-highlight-danger-label-hover)',
	'pill-invalid-border': 'var(--pill-invalid-border)',
	'pill-invalid-label': 'var(--pill-invalid-label)',
	'pill-invalid-background': 'var(--pill-invalid-background)',
	'pill-invalid-dismiss-icon': 'var(--pill-invalid-dismiss-icon)',
	'pill-invalid-dismiss-icon-hover': 'var(--pill-invalid-dismiss-icon-hover)',
	'pill-focus-ring': 'var(--pill-focus-ring)',
	'badge-primary-outlined-background':
		'var(--badge-primary-outlined-background)',
	'badge-primary-outlined-border': 'var(--badge-primary-outlined-border)',
	'badge-primary-outlined-label': 'var(--badge-primary-outlined-label)',
	'badge-primary-outlined-icon': 'var(--badge-primary-outlined-icon)',
	'badge-success-outlined-background':
		'var(--badge-success-outlined-background)',
	'badge-success-outlined-border': 'var(--badge-success-outlined-border)',
	'badge-success-outlined-label': 'var(--badge-success-outlined-label)',
	'badge-success-outlined-icon': 'var(--badge-success-outlined-icon)',
	'badge-warning-outlined-background':
		'var(--badge-warning-outlined-background)',
	'badge-warning-outlined-border': 'var(--badge-warning-outlined-border)',
	'badge-warning-outlined-label': 'var(--badge-warning-outlined-label)',
	'badge-warning-outlined-icon': 'var(--badge-warning-outlined-icon)',
	'badge-danger-outlined-background': 'var(--badge-danger-outlined-background)',
	'badge-danger-outlined-border': 'var(--badge-danger-outlined-border)',
	'badge-danger-outlined-label': 'var(--badge-danger-outlined-label)',
	'badge-danger-outlined-icon': 'var(--badge-danger-outlined-icon)',
	'badge-secondary-outlined-background':
		'var(--badge-secondary-outlined-background)',
	'badge-secondary-outlined-border': 'var(--badge-secondary-outlined-border)',
	'badge-secondary-outlined-label': 'var(--badge-secondary-outlined-label)',
	'badge-secondary-outlined-icon': 'var(--badge-secondary-outlined-icon)',
	'badge-primary-background': 'var(--badge-primary-background)',
	'badge-primary-foreground': 'var(--badge-primary-foreground)',
	'badge-secondary-background': 'var(--badge-secondary-background)',
	'badge-secondary-foreground': 'var(--badge-secondary-foreground)',
	'badge-success-background': 'var(--badge-success-background)',
	'badge-success-foreground': 'var(--badge-success-foreground)',
	'badge-warning-background': 'var(--badge-warning-background)',
	'badge-warning-foreground': 'var(--badge-warning-foreground)',
	'badge-danger-background': 'var(--badge-danger-background)',
	'badge-danger-foreground': 'var(--badge-danger-foreground)',
	'badge-info-background': 'var(--badge-info-background)',
	'badge-info-foreground': 'var(--badge-info-foreground)',
	'badge-archive-background': 'var(--badge-archive-background)',
	'badge-archive-foreground': 'var(--badge-archive-foreground)',
	'badge-highlight-danger-background':
		'var(--badge-highlight-danger-background)',
	'badge-highlight-danger-foreground':
		'var(--badge-highlight-danger-foreground)',
	'badge-secondary-border': 'var(--badge-secondary-border)',
	'badge-info-outlined-background': 'var(--badge-info-outlined-background)',
	'badge-info-outlined-border': 'var(--badge-info-outlined-border)',
	'badge-info-outlined-label': 'var(--badge-info-outlined-label)',
	'badge-archive-outlined-background':
		'var(--badge-archive-outlined-background)',
	'badge-archive-outlined-border': 'var(--badge-archive-outlined-border)',
	'badge-archive-outlined-label': 'var(--badge-archive-outlined-label)',
	'badge-highlight-danger-outlined-background':
		'var(--badge-highlight-danger-outlined-background)',
	'badge-highlight-danger-outlined-border':
		'var(--badge-highlight-danger-outlined-border)',
	'badge-highlight-danger-outlined-label':
		'var(--badge-highlight-danger-outlined-label)',
	'radio-group-border': 'var(--radio-group-border)',
	'radio-group-label': 'var(--radio-group-label)',
	'radio-group-label-hover': 'var(--radio-group-label-hover)',
	'radio-group-primary-background': 'var(--radio-group-primary-background)',
	'radio-group-primary-border-hover': 'var(--radio-group-primary-border-hover)',
	'radio-group-primary-dot': 'var(--radio-group-primary-dot)',
	'radio-group-secondary-background': 'var(--radio-group-secondary-background)',
	'radio-group-secondary-border-hover':
		'var(--radio-group-secondary-border-hover)',
	'radio-group-secondary-dot': 'var(--radio-group-secondary-dot)',
	'radio-group-success-background': 'var(--radio-group-success-background)',
	'radio-group-success-border-hover': 'var(--radio-group-success-border-hover)',
	'radio-group-success-dot': 'var(--radio-group-success-dot)',
	'radio-group-warning-background': 'var(--radio-group-warning-background)',
	'radio-group-warning-border-hover': 'var(--radio-group-warning-border-hover)',
	'radio-group-warning-dot': 'var(--radio-group-warning-dot)',
	'radio-group-danger-background': 'var(--radio-group-danger-background)',
	'radio-group-danger-border-hover': 'var(--radio-group-danger-border-hover)',
	'radio-group-danger-dot': 'var(--radio-group-danger-dot)',
	'radio-group-info-background': 'var(--radio-group-info-background)',
	'radio-group-info-border-hover': 'var(--radio-group-info-border-hover)',
	'radio-group-info-dot': 'var(--radio-group-info-dot)',
	'radio-group-archive-background': 'var(--radio-group-archive-background)',
	'radio-group-archive-border-hover': 'var(--radio-group-archive-border-hover)',
	'radio-group-archive-dot': 'var(--radio-group-archive-dot)',
	'radio-group-highlight-danger-background':
		'var(--radio-group-highlight-danger-background)',
	'radio-group-highlight-danger-border-hover':
		'var(--radio-group-highlight-danger-border-hover)',
	'radio-group-highlight-danger-dot': 'var(--radio-group-highlight-danger-dot)',
	'radio-group-focus-ring': 'var(--radio-group-focus-ring)',
	'switch-track-background': 'var(--switch-track-background)',
	'switch-track-hover-background': 'var(--switch-track-hover-background)',
	'switch-primary-background': 'var(--switch-primary-background)',
	'switch-primary-hover-background': 'var(--switch-primary-hover-background)',
	'switch-secondary-background': 'var(--switch-secondary-background)',
	'switch-secondary-hover-background':
		'var(--switch-secondary-hover-background)',
	'switch-success-background': 'var(--switch-success-background)',
	'switch-success-hover-background': 'var(--switch-success-hover-background)',
	'switch-warning-background': 'var(--switch-warning-background)',
	'switch-warning-hover-background': 'var(--switch-warning-hover-background)',
	'switch-danger-background': 'var(--switch-danger-background)',
	'switch-danger-hover-background': 'var(--switch-danger-hover-background)',
	'switch-info-background': 'var(--switch-info-background)',
	'switch-info-hover-background': 'var(--switch-info-hover-background)',
	'switch-archive-background': 'var(--switch-archive-background)',
	'switch-archive-hover-background': 'var(--switch-archive-hover-background)',
	'switch-highlight-danger-background':
		'var(--switch-highlight-danger-background)',
	'switch-highlight-danger-hover-background':
		'var(--switch-highlight-danger-hover-background)',
	'switch-thumb-background': 'var(--switch-thumb-background)',
	'switch-label': 'var(--switch-label)',
	'switch-description': 'var(--switch-description)',
	'switch-focus-ring': 'var(--switch-focus-ring)',
	'tabs-border': 'var(--tabs-border)',
	'tabs-primary-label': 'var(--tabs-primary-label)',
	'tabs-primary-label-hover': 'var(--tabs-primary-label-hover)',
	'tabs-primary-background-hover': 'var(--tabs-primary-background-hover)',
	'tabs-primary-indicator': 'var(--tabs-primary-indicator)',
	'tabs-primary-radius': 'var(--tabs-primary-radius)',
	'tabs-secondary-background': 'var(--tabs-secondary-background)',
	'tabs-secondary-background-hover': 'var(--tabs-secondary-background-hover)',
	'tabs-secondary-label': 'var(--tabs-secondary-label)',
	'tabs-secondary-label-hover': 'var(--tabs-secondary-label-hover)',
	'tabs-secondary-label-active': 'var(--tabs-secondary-label-active)',
	'tabs-secondary-label-disabled': 'var(--tabs-secondary-label-disabled)',
	'tabs-secondary-stripe-disabled': 'var(--tabs-secondary-stripe-disabled)',
	'tabs-label': 'var(--tabs-label)',
	'tabs-label-hover': 'var(--tabs-label-hover)',
	'tabs-hover-slider-background': 'var(--tabs-hover-slider-background)',
	'tabs-focus-ring': 'var(--tabs-focus-ring)',
	'tabs-focus-ring-offset': 'var(--tabs-focus-ring-offset)',
	'toggle-group-border': 'var(--toggle-group-border)',
	'toggle-group-secondary-outlined-background':
		'var(--toggle-group-secondary-outlined-background)',
	'toggle-group-secondary-outlined-background-hover':
		'var(--toggle-group-secondary-outlined-background-hover)',
	'toggle-group-secondary-outlined-background-active':
		'var(--toggle-group-secondary-outlined-background-active)',
	'toggle-group-secondary-outlined-label':
		'var(--toggle-group-secondary-outlined-label)',
	'toggle-group-secondary-outlined-label-hover':
		'var(--toggle-group-secondary-outlined-label-hover)',
	'toggle-group-secondary-outlined-label-active':
		'var(--toggle-group-secondary-outlined-label-active)',
	'toggle-group-secondary-outlined-label-disabled':
		'var(--toggle-group-secondary-outlined-label-disabled)',
	'toggle-group-scroll-button-background':
		'var(--toggle-group-scroll-button-background)',
	'toggle-group-scroll-button-background-hover':
		'var(--toggle-group-scroll-button-background-hover)',
	'toggle-group-scroll-button-label': 'var(--toggle-group-scroll-button-label)',
	'toggle-group-scroll-button-label-hover':
		'var(--toggle-group-scroll-button-label-hover)',
	'toggle-group-scroll-button-shadow-color':
		'var(--toggle-group-scroll-button-shadow-color)',
	'toggle-group-focus-ring': 'var(--toggle-group-focus-ring)',
	'dropdown-background': 'var(--dropdown-background)',
	'dropdown-border': 'var(--dropdown-border)',
	'dropdown-shadow': 'var(--dropdown-shadow)',
	'dropdown-item-label': 'var(--dropdown-item-label)',
	'dropdown-item-label-hover': 'var(--dropdown-item-label-hover)',
	'dropdown-item-label-disabled': 'var(--dropdown-item-label-disabled)',
	'dropdown-item-background': 'var(--dropdown-item-background)',
	'dropdown-item-background-hover': 'var(--dropdown-item-background-hover)',
	'dropdown-item-danger-label': 'var(--dropdown-item-danger-label)',
	'dropdown-item-danger-label-hover': 'var(--dropdown-item-danger-label-hover)',
	'dropdown-item-danger-background-hover':
		'var(--dropdown-item-danger-background-hover)',
	'dropdown-item-icon': 'var(--dropdown-item-icon)',
	'dropdown-item-icon-hover': 'var(--dropdown-item-icon-hover)',
	'dropdown-group-label': 'var(--dropdown-group-label)',
	'dropdown-separator': 'var(--dropdown-separator)',
	'dropdown-search-placeholder': 'var(--dropdown-search-placeholder)',
	'dropdown-search-icon': 'var(--dropdown-search-icon)',
	'dropdown-search-border': 'var(--dropdown-search-border)',
	'dropdown-loading-label': 'var(--dropdown-loading-label)',
	'dropdown-item-focus-ring': 'var(--dropdown-item-focus-ring)',
	'dropdown-scroll-fade': 'var(--dropdown-scroll-fade)',
	'dropdown-item-control-border': 'var(--dropdown-item-control-border)',
	'dropdown-item-control-border-hover':
		'var(--dropdown-item-control-border-hover)',
	'dropdown-item-control-checked-background':
		'var(--dropdown-item-control-checked-background)',
	'dropdown-item-control-checked-foreground':
		'var(--dropdown-item-control-checked-foreground)',
	'combobox-trigger-background': 'var(--combobox-trigger-background)',
	'combobox-trigger-border': 'var(--combobox-trigger-border)',
	'combobox-trigger-border-hover': 'var(--combobox-trigger-border-hover)',
	'combobox-trigger-focus-ring': 'var(--combobox-trigger-focus-ring)',
	'combobox-trigger-label': 'var(--combobox-trigger-label)',
	'combobox-trigger-label-disabled': 'var(--combobox-trigger-label-disabled)',
	'combobox-trigger-placeholder': 'var(--combobox-trigger-placeholder)',
	'combobox-trigger-icon': 'var(--combobox-trigger-icon)',
	'combobox-trigger-icon-hover': 'var(--combobox-trigger-icon-hover)',
	'combobox-chip-background': 'var(--combobox-chip-background)',
	'combobox-chip-label': 'var(--combobox-chip-label)',
	'combobox-chip-remove-icon': 'var(--combobox-chip-remove-icon)',
	'combobox-chip-remove-icon-hover': 'var(--combobox-chip-remove-icon-hover)',
	'combobox-background': 'var(--combobox-background)',
	'combobox-border': 'var(--combobox-border)',
	'combobox-shadow': 'var(--combobox-shadow)',
	'combobox-item-label': 'var(--combobox-item-label)',
	'combobox-item-label-hover': 'var(--combobox-item-label-hover)',
	'combobox-item-label-disabled': 'var(--combobox-item-label-disabled)',
	'combobox-item-background': 'var(--combobox-item-background)',
	'combobox-item-background-hover': 'var(--combobox-item-background-hover)',
	'combobox-item-icon': 'var(--combobox-item-icon)',
	'combobox-item-icon-hover': 'var(--combobox-item-icon-hover)',
	'combobox-item-indicator': 'var(--combobox-item-indicator)',
	'combobox-item-control-border': 'var(--combobox-item-control-border)',
	'combobox-item-control-border-hover':
		'var(--combobox-item-control-border-hover)',
	'combobox-item-control-checked-background':
		'var(--combobox-item-control-checked-background)',
	'combobox-item-control-checked-foreground':
		'var(--combobox-item-control-checked-foreground)',
	'combobox-group-label': 'var(--combobox-group-label)',
	'combobox-separator': 'var(--combobox-separator)',
	'combobox-search-placeholder': 'var(--combobox-search-placeholder)',
	'combobox-search-icon': 'var(--combobox-search-icon)',
	'combobox-search-border': 'var(--combobox-search-border)',
	'combobox-loading-label': 'var(--combobox-loading-label)',
	'combobox-empty-label': 'var(--combobox-empty-label)',
	'select-trigger-background': 'var(--select-trigger-background)',
	'select-trigger-border': 'var(--select-trigger-border)',
	'select-trigger-border-hover': 'var(--select-trigger-border-hover)',
	'select-trigger-focus-ring': 'var(--select-trigger-focus-ring)',
	'select-trigger-label': 'var(--select-trigger-label)',
	'select-trigger-label-disabled': 'var(--select-trigger-label-disabled)',
	'select-trigger-placeholder': 'var(--select-trigger-placeholder)',
	'select-trigger-icon': 'var(--select-trigger-icon)',
	'select-chip-background': 'var(--select-chip-background)',
	'select-chip-label': 'var(--select-chip-label)',
	'select-chip-remove-icon': 'var(--select-chip-remove-icon)',
	'select-chip-remove-icon-hover': 'var(--select-chip-remove-icon-hover)',
	'select-background': 'var(--select-background)',
	'select-border': 'var(--select-border)',
	'select-shadow': 'var(--select-shadow)',
	'select-item-label': 'var(--select-item-label)',
	'select-item-label-hover': 'var(--select-item-label-hover)',
	'select-item-label-disabled': 'var(--select-item-label-disabled)',
	'select-item-background': 'var(--select-item-background)',
	'select-item-background-hover': 'var(--select-item-background-hover)',
	'select-item-icon': 'var(--select-item-icon)',
	'select-item-icon-hover': 'var(--select-item-icon-hover)',
	'select-item-indicator': 'var(--select-item-indicator)',
	'select-item-control-border': 'var(--select-item-control-border)',
	'select-item-control-border-hover': 'var(--select-item-control-border-hover)',
	'select-item-control-checked-background':
		'var(--select-item-control-checked-background)',
	'select-item-control-checked-foreground':
		'var(--select-item-control-checked-foreground)',
	'select-group-label': 'var(--select-group-label)',
	'select-separator': 'var(--select-separator)',
	'select-loading-label': 'var(--select-loading-label)',
	'select-empty-label': 'var(--select-empty-label)',
	'calendar-background': 'var(--calendar-background)',
	'calendar-button-background': 'var(--calendar-button-background)',
	'calendar-button-background-hover': 'var(--calendar-button-background-hover)',
	'calendar-button-background-active':
		'var(--calendar-button-background-active)',
	'calendar-button-label': 'var(--calendar-button-label)',
	'calendar-button-label-hover': 'var(--calendar-button-label-hover)',
	'calendar-button-focus-ring': 'var(--calendar-button-focus-ring)',
	'calendar-day-selected-background': 'var(--calendar-day-selected-background)',
	'calendar-day-selected-background-hover':
		'var(--calendar-day-selected-background-hover)',
	'calendar-day-selected-label': 'var(--calendar-day-selected-label)',
	'calendar-day-range-edge-background':
		'var(--calendar-day-range-edge-background)',
	'calendar-day-range-edge-background-hover':
		'var(--calendar-day-range-edge-background-hover)',
	'calendar-day-range-edge-label': 'var(--calendar-day-range-edge-label)',
	'calendar-day-range-middle-background':
		'var(--calendar-day-range-middle-background)',
	'calendar-day-range-middle-background-hover':
		'var(--calendar-day-range-middle-background-hover)',
	'calendar-day-range-middle-label': 'var(--calendar-day-range-middle-label)',
	'calendar-day-today-background': 'var(--calendar-day-today-background)',
	'calendar-day-today-label': 'var(--calendar-day-today-label)',
	'calendar-day-outside-label': 'var(--calendar-day-outside-label)',
	'calendar-day-disabled-label': 'var(--calendar-day-disabled-label)',
	'calendar-weekday-label': 'var(--calendar-weekday-label)',
	'calendar-week-number-label': 'var(--calendar-week-number-label)',
	'calendar-select-background': 'var(--calendar-select-background)',
	'calendar-select-border': 'var(--calendar-select-border)',
	'calendar-select-border-focus': 'var(--calendar-select-border-focus)',
	'calendar-select-icon': 'var(--calendar-select-icon)',
	'calendar-select-shadow': 'var(--calendar-select-shadow)',
	'calendar-select-shadow-focus': 'var(--calendar-select-shadow-focus)',
	'button-group-secondary-outlined-background':
		'var(--button-group-secondary-outlined-background)',
	'button-group-secondary-outlined-background-hover':
		'var(--button-group-secondary-outlined-background-hover)',
	'button-group-secondary-outlined-label':
		'var(--button-group-secondary-outlined-label)',
	'button-group-secondary-outlined-label-hover':
		'var(--button-group-secondary-outlined-label-hover)',
	'button-group-secondary-outlined-border':
		'var(--button-group-secondary-outlined-border)',
	'button-group-secondary-outlined-disabled-stripe':
		'var(--button-group-secondary-outlined-disabled-stripe)',
	'button-group-focus-ring': 'var(--button-group-focus-ring)',
	'checkbox-border': 'var(--checkbox-border)',
	'checkbox-label': 'var(--checkbox-label)',
	'checkbox-primary-background': 'var(--checkbox-primary-background)',
	'checkbox-primary-foreground': 'var(--checkbox-primary-foreground)',
	'checkbox-primary-border-hover': 'var(--checkbox-primary-border-hover)',
	'checkbox-secondary-background': 'var(--checkbox-secondary-background)',
	'checkbox-secondary-foreground': 'var(--checkbox-secondary-foreground)',
	'checkbox-secondary-border-hover': 'var(--checkbox-secondary-border-hover)',
	'checkbox-success-background': 'var(--checkbox-success-background)',
	'checkbox-success-foreground': 'var(--checkbox-success-foreground)',
	'checkbox-success-border-hover': 'var(--checkbox-success-border-hover)',
	'checkbox-warning-background': 'var(--checkbox-warning-background)',
	'checkbox-warning-foreground': 'var(--checkbox-warning-foreground)',
	'checkbox-warning-border-hover': 'var(--checkbox-warning-border-hover)',
	'checkbox-danger-background': 'var(--checkbox-danger-background)',
	'checkbox-danger-foreground': 'var(--checkbox-danger-foreground)',
	'checkbox-danger-border-hover': 'var(--checkbox-danger-border-hover)',
	'checkbox-info-background': 'var(--checkbox-info-background)',
	'checkbox-info-foreground': 'var(--checkbox-info-foreground)',
	'checkbox-info-border-hover': 'var(--checkbox-info-border-hover)',
	'checkbox-archive-background': 'var(--checkbox-archive-background)',
	'checkbox-archive-foreground': 'var(--checkbox-archive-foreground)',
	'checkbox-archive-border-hover': 'var(--checkbox-archive-border-hover)',
	'checkbox-highlight-danger-background':
		'var(--checkbox-highlight-danger-background)',
	'checkbox-highlight-danger-foreground':
		'var(--checkbox-highlight-danger-foreground)',
	'checkbox-highlight-danger-border-hover':
		'var(--checkbox-highlight-danger-border-hover)',
	'checkbox-focus-ring': 'var(--checkbox-focus-ring)',
	'button-primary-background': 'var(--button-primary-background)',
	'button-primary-background-hover': 'var(--button-primary-background-hover)',
	'button-primary-label': 'var(--button-primary-label)',
	'button-primary-link': 'var(--button-primary-link)',
	'button-primary-link-hover': 'var(--button-primary-link-hover)',
	'button-secondary-background': 'var(--button-secondary-background)',
	'button-secondary-background-hover':
		'var(--button-secondary-background-hover)',
	'button-secondary-label': 'var(--button-secondary-label)',
	'button-secondary-link': 'var(--button-secondary-link)',
	'button-secondary-link-hover': 'var(--button-secondary-link-hover)',
	'button-success-background': 'var(--button-success-background)',
	'button-success-background-hover': 'var(--button-success-background-hover)',
	'button-success-label': 'var(--button-success-label)',
	'button-success-link': 'var(--button-success-link)',
	'button-success-link-hover': 'var(--button-success-link-hover)',
	'button-warning-background': 'var(--button-warning-background)',
	'button-warning-background-hover': 'var(--button-warning-background-hover)',
	'button-warning-label': 'var(--button-warning-label)',
	'button-warning-link': 'var(--button-warning-link)',
	'button-warning-link-hover': 'var(--button-warning-link-hover)',
	'button-danger-background': 'var(--button-danger-background)',
	'button-danger-background-hover': 'var(--button-danger-background-hover)',
	'button-danger-label': 'var(--button-danger-label)',
	'button-danger-link': 'var(--button-danger-link)',
	'button-danger-link-hover': 'var(--button-danger-link-hover)',
	'button-info-background': 'var(--button-info-background)',
	'button-info-background-hover': 'var(--button-info-background-hover)',
	'button-info-label': 'var(--button-info-label)',
	'button-info-link': 'var(--button-info-link)',
	'button-info-link-hover': 'var(--button-info-link-hover)',
	'button-archive-background': 'var(--button-archive-background)',
	'button-archive-background-hover': 'var(--button-archive-background-hover)',
	'button-archive-label': 'var(--button-archive-label)',
	'button-archive-link': 'var(--button-archive-link)',
	'button-archive-link-hover': 'var(--button-archive-link-hover)',
	'button-highlight-danger-background':
		'var(--button-highlight-danger-background)',
	'button-highlight-danger-background-hover':
		'var(--button-highlight-danger-background-hover)',
	'button-highlight-danger-label': 'var(--button-highlight-danger-label)',
	'button-highlight-danger-link': 'var(--button-highlight-danger-link)',
	'button-highlight-danger-link-hover':
		'var(--button-highlight-danger-link-hover)',
	'button-secondary-outlined-background':
		'var(--button-secondary-outlined-background)',
	'button-secondary-outlined-background-hover':
		'var(--button-secondary-outlined-background-hover)',
	'button-secondary-outlined-label': 'var(--button-secondary-outlined-label)',
	'button-secondary-outlined-label-hover':
		'var(--button-secondary-outlined-label-hover)',
	'button-secondary-outlined-border': 'var(--button-secondary-outlined-border)',
	'button-secondary-outlined-disabled-stripe':
		'var(--button-secondary-outlined-disabled-stripe)',
	'button-secondary-dashed-label': 'var(--button-secondary-dashed-label)',
	'button-secondary-dashed-label-hover':
		'var(--button-secondary-dashed-label-hover)',
	'button-secondary-dashed-stroke': 'var(--button-secondary-dashed-stroke)',
	'button-secondary-dashed-stroke-hover':
		'var(--button-secondary-dashed-stroke-hover)',
	'button-secondary-ghost-label': 'var(--button-secondary-ghost-label)',
	'button-secondary-ghost-label-hover':
		'var(--button-secondary-ghost-label-hover)',
	'button-secondary-ghost-background-hover':
		'var(--button-secondary-ghost-background-hover)',
	'button-ghost-glow-opacity': 'var(--button-ghost-glow-opacity)',
	'button-focus-ring': 'var(--button-focus-ring)',
	'tooltip-background': 'var(--tooltip-background)',
	'tooltip-label': 'var(--tooltip-label)',
	'tooltip-border': 'var(--tooltip-border)',
	'tooltip-divider': 'var(--tooltip-divider)',
	'tooltip-shadow': 'var(--tooltip-shadow)',
	'toast-background': 'var(--toast-background)',
	'toast-border': 'var(--toast-border)',
	'toast-shadow': 'var(--toast-shadow)',
	'toast-title': 'var(--toast-title)',
	'toast-description': 'var(--toast-description)',
	'toast-info-icon': 'var(--toast-info-icon)',
	'toast-success-icon': 'var(--toast-success-icon)',
	'toast-warning-icon': 'var(--toast-warning-icon)',
	'toast-danger-icon': 'var(--toast-danger-icon)',
	'toast-loading-icon': 'var(--toast-loading-icon)',
	'toast-action-label': 'var(--toast-action-label)',
	'toast-action-label-hover': 'var(--toast-action-label-hover)',
	'toast-action-background-hover': 'var(--toast-action-background-hover)',
	'toast-action-divider': 'var(--toast-action-divider)',
	'toast-focus-ring': 'var(--toast-focus-ring)',
	'size-icon-toast': 'var(--size-icon-toast)',
	'progress-track': 'var(--progress-track)',
	'progress-value': 'var(--progress-value)',
	'progress-primary-indicator': 'var(--progress-primary-indicator)',
	'progress-secondary-indicator': 'var(--progress-secondary-indicator)',
	'progress-success-indicator': 'var(--progress-success-indicator)',
	'progress-danger-indicator': 'var(--progress-danger-indicator)',
	'progress-warning-indicator': 'var(--progress-warning-indicator)',
	'progress-info-indicator': 'var(--progress-info-indicator)',
	'progress-archive-indicator': 'var(--progress-archive-indicator)',
	'progress-highlight-danger-indicator':
		'var(--progress-highlight-danger-indicator)',
	'progress-active-stripe': 'var(--progress-active-stripe)',
	'slider-primary-indicator': 'var(--slider-primary-indicator)',
	'slider-secondary-indicator': 'var(--slider-secondary-indicator)',
	'slider-success-indicator': 'var(--slider-success-indicator)',
	'slider-danger-indicator': 'var(--slider-danger-indicator)',
	'slider-warning-indicator': 'var(--slider-warning-indicator)',
	'slider-info-indicator': 'var(--slider-info-indicator)',
	'slider-archive-indicator': 'var(--slider-archive-indicator)',
	'slider-highlight-danger-indicator':
		'var(--slider-highlight-danger-indicator)',
	'command-background': 'var(--command-background)',
	'command-backdrop': 'var(--command-backdrop)',
	'command-border': 'var(--command-border)',
	'command-shadow': 'var(--command-shadow)',
	'command-item-label': 'var(--command-item-label)',
	'command-item-label-hover': 'var(--command-item-label-hover)',
	'command-item-label-disabled': 'var(--command-item-label-disabled)',
	'command-item-background': 'var(--command-item-background)',
	'command-item-background-hover': 'var(--command-item-background-hover)',
	'command-item-icon': 'var(--command-item-icon)',
	'command-item-icon-hover': 'var(--command-item-icon-hover)',
	'command-group-label': 'var(--command-group-label)',
	'command-search-placeholder': 'var(--command-search-placeholder)',
	'command-search-icon': 'var(--command-search-icon)',
	'command-search-border': 'var(--command-search-border)',
	'command-empty-label': 'var(--command-empty-label)',
	'divider-border': 'var(--divider-border)',
	'divider-label': 'var(--divider-label)',
	'radio-cards-background': 'var(--radio-cards-background)',
	'radio-cards-background-hover': 'var(--radio-cards-background-hover)',
	'radio-cards-border': 'var(--radio-cards-border)',
	'radio-cards-label': 'var(--radio-cards-label)',
	'radio-cards-label-hover': 'var(--radio-cards-label-hover)',
	'radio-cards-icon': 'var(--radio-cards-icon)',
	'radio-cards-icon-hover': 'var(--radio-cards-icon-hover)',
	'radio-cards-checked-background': 'var(--radio-cards-checked-background)',
	'radio-cards-checked-border': 'var(--radio-cards-checked-border)',
	'radio-cards-checked-label': 'var(--radio-cards-checked-label)',
	'radio-cards-checked-icon': 'var(--radio-cards-checked-icon)',
	'radio-cards-focus-ring': 'var(--radio-cards-focus-ring)',
	'breadcrumb-label': 'var(--breadcrumb-label)',
	'breadcrumb-label-hover': 'var(--breadcrumb-label-hover)',
	'breadcrumb-background-hover': 'var(--breadcrumb-background-hover)',
	'breadcrumb-focus-ring': 'var(--breadcrumb-focus-ring)',
	'input-background': 'var(--input-background)',
	'input-border': 'var(--input-border)',
	'input-border-hover': 'var(--input-border-hover)',
	'input-foreground': 'var(--input-foreground)',
	'input-placeholder': 'var(--input-placeholder)',
	'input-placeholder-hover': 'var(--input-placeholder-hover)',
	'input-icon': 'var(--input-icon)',
	'input-focus-ring': 'var(--input-focus-ring)',
	'input-success-background': 'var(--input-success-background)',
	'input-success-border': 'var(--input-success-border)',
	'input-success-icon': 'var(--input-success-icon)',
	'input-warning-background': 'var(--input-warning-background)',
	'input-warning-border': 'var(--input-warning-border)',
	'input-warning-icon': 'var(--input-warning-icon)',
	'input-danger-background': 'var(--input-danger-background)',
	'input-danger-border': 'var(--input-danger-border)',
	'input-danger-icon': 'var(--input-danger-icon)',
	'field-label': 'var(--field-label)',
	'field-label-hover': 'var(--field-label-hover)',
	'field-label-icon': 'var(--field-label-icon)',
	'field-required-marker': 'var(--field-required-marker)',
	'field-success-label': 'var(--field-success-label)',
	'field-success-message': 'var(--field-success-message)',
	'field-success-icon': 'var(--field-success-icon)',
	'field-warning-label': 'var(--field-warning-label)',
	'field-warning-message': 'var(--field-warning-message)',
	'field-warning-icon': 'var(--field-warning-icon)',
	'field-danger-label': 'var(--field-danger-label)',
	'field-danger-message': 'var(--field-danger-message)',
	'field-danger-icon': 'var(--field-danger-icon)',
} as const;

export type StyleTailwindType =
	(typeof StyleTailwind)[keyof typeof StyleTailwind];
