/**
 * Semantic Token Constants
 * DO NOT EDIT DIRECTLY - This file is auto-generated
 * Generated on Thu, 24 Sep 2026 14:58:56 GMT
 */

export const Style = {
	BACKGROUND: 'var(--background)',
	FOREGROUND: 'var(--foreground)',
	CARD: 'var(--card)',
	CARD_FOREGROUND: 'var(--card-foreground)',
	POPOVER: 'var(--popover)',
	POPOVER_FOREGROUND: 'var(--popover-foreground)',
	PRIMARY: 'var(--primary)',
	SECONDARY: 'var(--secondary)',
	MUTED: 'var(--muted)',
	MUTED_FOREGROUND: 'var(--muted-foreground)',
	ACCENT: 'var(--accent)',
	ACCENT_FOREGROUND: 'var(--accent-foreground)',
	DESTRUCTIVE: 'var(--destructive)',
	DESTRUCTIVE_FOREGROUND: 'var(--destructive-foreground)',
	BORDER: 'var(--border)',
	INPUT: 'var(--input)',
	RING: 'var(--ring)',
	RADIUS: 'var(--radius)',
	CHART_1: 'var(--chart-1)',
	CHART_2: 'var(--chart-2)',
	CHART_3: 'var(--chart-3)',
	CHART_4: 'var(--chart-4)',
	CHART_5: 'var(--chart-5)',
	SIDEBAR: 'var(--sidebar)',
	SIDEBAR_FOREGROUND: 'var(--sidebar-foreground)',
	SIDEBAR_PRIMARY: 'var(--sidebar-primary)',
	SIDEBAR_PRIMARY_FOREGROUND: 'var(--sidebar-primary-foreground)',
	SIDEBAR_ACCENT: 'var(--sidebar-accent)',
	SIDEBAR_ACCENT_FOREGROUND: 'var(--sidebar-accent-foreground)',
	SIDEBAR_BORDER: 'var(--sidebar-border)',
	SIDEBAR_RING: 'var(--sidebar-ring)',
	FONT_SANS: 'var(--font-sans)',
	FONT_SERIF: 'var(--font-serif)',
	FONT_MONO: 'var(--font-mono)',
	BASE_WHITE: 'var(--base-white)',
	BASE_BLACK: 'var(--base-black)',
	L1_BACKGROUND: 'var(--l1-background)',
	L2_BACKGROUND: 'var(--l2-background)',
	L3_BACKGROUND: 'var(--l3-background)',
	L1_BACKGROUND_HOVER: 'var(--l1-background-hover)',
	L2_BACKGROUND_HOVER: 'var(--l2-background-hover)',
	L3_BACKGROUND_HOVER: 'var(--l3-background-hover)',
	L1_FOREGROUND: 'var(--l1-foreground)',
	L1_FOREGROUND_HOVER: 'var(--l1-foreground-hover)',
	L2_FOREGROUND: 'var(--l2-foreground)',
	L2_FOREGROUND_HOVER: 'var(--l2-foreground-hover)',
	L3_FOREGROUND: 'var(--l3-foreground)',
	L3_FOREGROUND_HOVER: 'var(--l3-foreground-hover)',
	L1_BORDER: 'var(--l1-border)',
	L2_BORDER: 'var(--l2-border)',
	L3_BORDER: 'var(--l3-border)',
	PRIMARY_BACKGROUND: 'var(--primary-background)',
	PRIMARY_BACKGROUND_HOVER: 'var(--primary-background-hover)',
	PRIMARY_FOREGROUND: 'var(--primary-foreground)',
	PRIMARY_FOREGROUND_HOVER: 'var(--primary-foreground-hover)',
	SECONDARY_BACKGROUND: 'var(--secondary-background)',
	SECONDARY_BACKGROUND_HOVER: 'var(--secondary-background-hover)',
	SECONDARY_FOREGROUND: 'var(--secondary-foreground)',
	SECONDARY_FOREGROUND_HOVER: 'var(--secondary-foreground-hover)',
	SECONDARY_BORDER: 'var(--secondary-border)',
	SUCCESS_BACKGROUND: 'var(--success-background)',
	SUCCESS_BACKGROUND_HOVER: 'var(--success-background-hover)',
	SUCCESS_FOREGROUND: 'var(--success-foreground)',
	SUCCESS_FOREGROUND_HOVER: 'var(--success-foreground-hover)',
	WARNING_BACKGROUND: 'var(--warning-background)',
	WARNING_BACKGROUND_HOVER: 'var(--warning-background-hover)',
	WARNING_FOREGROUND: 'var(--warning-foreground)',
	WARNING_FOREGROUND_HOVER: 'var(--warning-foreground-hover)',
	DANGER_BACKGROUND: 'var(--danger-background)',
	DANGER_BACKGROUND_HOVER: 'var(--danger-background-hover)',
	DANGER_FOREGROUND: 'var(--danger-foreground)',
	DANGER_FOREGROUND_HOVER: 'var(--danger-foreground-hover)',
	PRIMARY_LINK: 'var(--primary-link)',
	PRIMARY_LINK_HOVER: 'var(--primary-link-hover)',
	SECONDARY_LINK: 'var(--secondary-link)',
	SECONDARY_LINK_HOVER: 'var(--secondary-link-hover)',
	SUCCESS_LINK: 'var(--success-link)',
	SUCCESS_LINK_HOVER: 'var(--success-link-hover)',
	WARNING_LINK: 'var(--warning-link)',
	WARNING_LINK_HOVER: 'var(--warning-link-hover)',
	DANGER_LINK: 'var(--danger-link)',
	DANGER_LINK_HOVER: 'var(--danger-link-hover)',
	L1_BACKGROUND_TRANSPARENT: 'var(--l1-background-transparent)',
	L1_BACKGROUND_60: 'var(--l1-background-60)',
	L2_BACKGROUND_TRANSPARENT: 'var(--l2-background-transparent)',
	L2_BACKGROUND_60: 'var(--l2-background-60)',
	L3_BACKGROUND_TRANSPARENT: 'var(--l3-background-transparent)',
	L3_BACKGROUND_60: 'var(--l3-background-60)',
	L3_BACKGROUND_30: 'var(--l3-background-30)',
	SURFACE_1: 'var(--surface-1)',
	SURFACE_2: 'var(--surface-2)',
	SURFACE_3: 'var(--surface-3)',
	SURFACE_STATIC: 'var(--surface-static)',
	ALERT_STRIP_BUTTON_BACKGROUND: 'var(--alert-strip-button-background)',
	CALLOUT_PRIMARY_BACKGROUND: 'var(--callout-primary-background)',
	CALLOUT_PRIMARY_BORDER: 'var(--callout-primary-border)',
	CALLOUT_PRIMARY_TITLE: 'var(--callout-primary-title)',
	CALLOUT_PRIMARY_DESCRIPTION: 'var(--callout-primary-description)',
	CALLOUT_PRIMARY_ICON: 'var(--callout-primary-icon)',
	CALLOUT_SUCCESS_BACKGROUND: 'var(--callout-success-background)',
	CALLOUT_SUCCESS_BORDER: 'var(--callout-success-border)',
	CALLOUT_SUCCESS_TITLE: 'var(--callout-success-title)',
	CALLOUT_SUCCESS_DESCRIPTION: 'var(--callout-success-description)',
	CALLOUT_SUCCESS_ICON: 'var(--callout-success-icon)',
	CALLOUT_WARNING_BACKGROUND: 'var(--callout-warning-background)',
	CALLOUT_WARNING_BORDER: 'var(--callout-warning-border)',
	CALLOUT_WARNING_TITLE: 'var(--callout-warning-title)',
	CALLOUT_WARNING_DESCRIPTION: 'var(--callout-warning-description)',
	CALLOUT_WARNING_ICON: 'var(--callout-warning-icon)',
	CALLOUT_ERROR_BACKGROUND: 'var(--callout-error-background)',
	CALLOUT_ERROR_BORDER: 'var(--callout-error-border)',
	CALLOUT_ERROR_TITLE: 'var(--callout-error-title)',
	CALLOUT_ERROR_DESCRIPTION: 'var(--callout-error-description)',
	CALLOUT_ERROR_ICON: 'var(--callout-error-icon)',
	ACCENT_PRIMARY: 'var(--accent-primary)',
	ACCENT_PRIMARY_HOVER: 'var(--accent-primary-hover)',
	ACCENT_PRIMARY_FOREGROUND: 'var(--accent-primary-foreground)',
	ACCENT_FOREST: 'var(--accent-forest)',
	ACCENT_FOREST_HOVER: 'var(--accent-forest-hover)',
	ACCENT_FOREST_FOREGROUND: 'var(--accent-forest-foreground)',
	ACCENT_AMBER: 'var(--accent-amber)',
	ACCENT_AMBER_HOVER: 'var(--accent-amber-hover)',
	ACCENT_AMBER_FOREGROUND: 'var(--accent-amber-foreground)',
	ACCENT_CHERRY: 'var(--accent-cherry)',
	ACCENT_CHERRY_HOVER: 'var(--accent-cherry-hover)',
	ACCENT_CHERRY_FOREGROUND: 'var(--accent-cherry-foreground)',
	ACCENT_AQUA: 'var(--accent-aqua)',
	ACCENT_AQUA_HOVER: 'var(--accent-aqua-hover)',
	ACCENT_AQUA_FOREGROUND: 'var(--accent-aqua-foreground)',
	ACCENT_SAKURA: 'var(--accent-sakura)',
	ACCENT_SAKURA_HOVER: 'var(--accent-sakura-hover)',
	ACCENT_SAKURA_FOREGROUND: 'var(--accent-sakura-foreground)',
	ACCENT_SIENNA: 'var(--accent-sienna)',
	ACCENT_SIENNA_HOVER: 'var(--accent-sienna-hover)',
	ACCENT_SIENNA_FOREGROUND: 'var(--accent-sienna-foreground)',
	GHOST_BACKGROUND: 'var(--ghost-background)',
	GHOST_BACKGROUND_HOVER: 'var(--ghost-background-hover)',
	GHOST_FOREGROUND: 'var(--ghost-foreground)',
	GHOST_FOREGROUND_HOVER: 'var(--ghost-foreground-hover)',
	GHOST_BORDER: 'var(--ghost-border)',
	ACTION_BACKGROUND: 'var(--action-background)',
	ACTION_BACKGROUND_HOVER: 'var(--action-background-hover)',
	ACTION_BORDER: 'var(--action-border)',
	ACTION_BORDER_HOVER: 'var(--action-border-hover)',
	ACTION_FOREGROUND: 'var(--action-foreground)',
	ACTION_FOREGROUND_HOVER: 'var(--action-foreground-hover)',
	CALLOUT_SIENNA_BACKGROUND: 'var(--callout-sienna-background)',
	CALLOUT_SIENNA_BORDER: 'var(--callout-sienna-border)',
	CALLOUT_SIENNA_TITLE: 'var(--callout-sienna-title)',
	CALLOUT_SIENNA_DESCRIPTION: 'var(--callout-sienna-description)',
	CALLOUT_SIENNA_ICON: 'var(--callout-sienna-icon)',
	CALLOUT_AQUA_BACKGROUND: 'var(--callout-aqua-background)',
	CALLOUT_AQUA_BORDER: 'var(--callout-aqua-border)',
	CALLOUT_AQUA_TITLE: 'var(--callout-aqua-title)',
	CALLOUT_AQUA_DESCRIPTION: 'var(--callout-aqua-description)',
	CALLOUT_AQUA_ICON: 'var(--callout-aqua-icon)',
	CONTROL_ICON_FOREGROUND: 'var(--control-icon-foreground)',
	CONTROL_ICON_FOREGROUND_CONTRAST: 'var(--control-icon-foreground-contrast)',
	SHADOW_SIDEBAR: 'var(--shadow-sidebar)',
	SHADOW_DROPDOWN: 'var(--shadow-dropdown)',
	SHADOW_DRAWER: 'var(--shadow-drawer)',
	SHADOW_DIALOG: 'var(--shadow-dialog)',
	SHADOW_TOAST: 'var(--shadow-toast)',
	SHADOW_TOOLTIP: 'var(--shadow-tooltip)',
	PILL_PRIMARY_BACKGROUND: 'var(--pill-primary-background)',
	PILL_PRIMARY_BORDER: 'var(--pill-primary-border)',
	PILL_PRIMARY_LABEL: 'var(--pill-primary-label)',
	PILL_PRIMARY_LABEL_HOVER: 'var(--pill-primary-label-hover)',
	PILL_SUCCESS_BACKGROUND: 'var(--pill-success-background)',
	PILL_SUCCESS_BORDER: 'var(--pill-success-border)',
	PILL_SUCCESS_LABEL: 'var(--pill-success-label)',
	PILL_SUCCESS_LABEL_HOVER: 'var(--pill-success-label-hover)',
	PILL_WARNING_BACKGROUND: 'var(--pill-warning-background)',
	PILL_WARNING_BORDER: 'var(--pill-warning-border)',
	PILL_WARNING_LABEL: 'var(--pill-warning-label)',
	PILL_WARNING_LABEL_HOVER: 'var(--pill-warning-label-hover)',
	PILL_DANGER_BACKGROUND: 'var(--pill-danger-background)',
	PILL_DANGER_BORDER: 'var(--pill-danger-border)',
	PILL_DANGER_LABEL: 'var(--pill-danger-label)',
	PILL_DANGER_LABEL_HOVER: 'var(--pill-danger-label-hover)',
	PILL_OUTLINED_BACKGROUND: 'var(--pill-outlined-background)',
	PILL_OUTLINED_BACKGROUND_HOVER: 'var(--pill-outlined-background-hover)',
	PILL_OUTLINED_BORDER: 'var(--pill-outlined-border)',
	PILL_OUTLINED_LABEL: 'var(--pill-outlined-label)',
	PILL_OUTLINED_LABEL_HOVER: 'var(--pill-outlined-label-hover)',
	PILL_RECT_SOLID_BACKGROUND: 'var(--pill-rect-solid-background)',
	PILL_RECT_SOLID_BACKGROUND_HOVER: 'var(--pill-rect-solid-background-hover)',
	PILL_RECT_SOLID_LABEL: 'var(--pill-rect-solid-label)',
	PILL_RECT_SOLID_LABEL_HOVER: 'var(--pill-rect-solid-label-hover)',
	PILL_RECT_SOLID_DISMISS_ICON: 'var(--pill-rect-solid-dismiss-icon)',
	PILL_RECT_SOLID_DISMISS_ICON_HOVER:
		'var(--pill-rect-solid-dismiss-icon-hover)',
	PILL_INFO_BACKGROUND: 'var(--pill-info-background)',
	PILL_INFO_BORDER: 'var(--pill-info-border)',
	PILL_INFO_LABEL: 'var(--pill-info-label)',
	PILL_INFO_LABEL_HOVER: 'var(--pill-info-label-hover)',
	PILL_ARCHIVE_BACKGROUND: 'var(--pill-archive-background)',
	PILL_ARCHIVE_BORDER: 'var(--pill-archive-border)',
	PILL_ARCHIVE_LABEL: 'var(--pill-archive-label)',
	PILL_ARCHIVE_LABEL_HOVER: 'var(--pill-archive-label-hover)',
	PILL_HIGHLIGHT_DANGER_BACKGROUND: 'var(--pill-highlight-danger-background)',
	PILL_HIGHLIGHT_DANGER_BORDER: 'var(--pill-highlight-danger-border)',
	PILL_HIGHLIGHT_DANGER_LABEL: 'var(--pill-highlight-danger-label)',
	PILL_HIGHLIGHT_DANGER_LABEL_HOVER: 'var(--pill-highlight-danger-label-hover)',
	PILL_INVALID_BORDER: 'var(--pill-invalid-border)',
	PILL_INVALID_LABEL: 'var(--pill-invalid-label)',
	PILL_FOCUS_RING: 'var(--pill-focus-ring)',
	BADGE_PRIMARY_OUTLINED_BACKGROUND: 'var(--badge-primary-outlined-background)',
	BADGE_PRIMARY_OUTLINED_BORDER: 'var(--badge-primary-outlined-border)',
	BADGE_PRIMARY_OUTLINED_LABEL: 'var(--badge-primary-outlined-label)',
	BADGE_PRIMARY_OUTLINED_ICON: 'var(--badge-primary-outlined-icon)',
	BADGE_SUCCESS_OUTLINED_BACKGROUND: 'var(--badge-success-outlined-background)',
	BADGE_SUCCESS_OUTLINED_BORDER: 'var(--badge-success-outlined-border)',
	BADGE_SUCCESS_OUTLINED_LABEL: 'var(--badge-success-outlined-label)',
	BADGE_SUCCESS_OUTLINED_ICON: 'var(--badge-success-outlined-icon)',
	BADGE_WARNING_OUTLINED_BACKGROUND: 'var(--badge-warning-outlined-background)',
	BADGE_WARNING_OUTLINED_BORDER: 'var(--badge-warning-outlined-border)',
	BADGE_WARNING_OUTLINED_LABEL: 'var(--badge-warning-outlined-label)',
	BADGE_WARNING_OUTLINED_ICON: 'var(--badge-warning-outlined-icon)',
	BADGE_DANGER_OUTLINED_BACKGROUND: 'var(--badge-danger-outlined-background)',
	BADGE_DANGER_OUTLINED_BORDER: 'var(--badge-danger-outlined-border)',
	BADGE_DANGER_OUTLINED_LABEL: 'var(--badge-danger-outlined-label)',
	BADGE_DANGER_OUTLINED_ICON: 'var(--badge-danger-outlined-icon)',
	BADGE_SECONDARY_OUTLINED_BACKGROUND:
		'var(--badge-secondary-outlined-background)',
	BADGE_SECONDARY_OUTLINED_BORDER: 'var(--badge-secondary-outlined-border)',
	BADGE_SECONDARY_OUTLINED_LABEL: 'var(--badge-secondary-outlined-label)',
	BADGE_SECONDARY_OUTLINED_ICON: 'var(--badge-secondary-outlined-icon)',
	BADGE_PRIMARY_BACKGROUND: 'var(--badge-primary-background)',
	BADGE_PRIMARY_FOREGROUND: 'var(--badge-primary-foreground)',
	BADGE_SECONDARY_BACKGROUND: 'var(--badge-secondary-background)',
	BADGE_SECONDARY_FOREGROUND: 'var(--badge-secondary-foreground)',
	BADGE_SUCCESS_BACKGROUND: 'var(--badge-success-background)',
	BADGE_SUCCESS_FOREGROUND: 'var(--badge-success-foreground)',
	BADGE_WARNING_BACKGROUND: 'var(--badge-warning-background)',
	BADGE_WARNING_FOREGROUND: 'var(--badge-warning-foreground)',
	BADGE_DANGER_BACKGROUND: 'var(--badge-danger-background)',
	BADGE_DANGER_FOREGROUND: 'var(--badge-danger-foreground)',
	BADGE_INFO_BACKGROUND: 'var(--badge-info-background)',
	BADGE_INFO_FOREGROUND: 'var(--badge-info-foreground)',
	BADGE_ARCHIVE_BACKGROUND: 'var(--badge-archive-background)',
	BADGE_ARCHIVE_FOREGROUND: 'var(--badge-archive-foreground)',
	BADGE_HIGHLIGHT_DANGER_BACKGROUND: 'var(--badge-highlight-danger-background)',
	BADGE_HIGHLIGHT_DANGER_FOREGROUND: 'var(--badge-highlight-danger-foreground)',
	BADGE_SECONDARY_BORDER: 'var(--badge-secondary-border)',
	BADGE_INFO_OUTLINED_BACKGROUND: 'var(--badge-info-outlined-background)',
	BADGE_INFO_OUTLINED_BORDER: 'var(--badge-info-outlined-border)',
	BADGE_INFO_OUTLINED_LABEL: 'var(--badge-info-outlined-label)',
	BADGE_ARCHIVE_OUTLINED_BACKGROUND: 'var(--badge-archive-outlined-background)',
	BADGE_ARCHIVE_OUTLINED_BORDER: 'var(--badge-archive-outlined-border)',
	BADGE_ARCHIVE_OUTLINED_LABEL: 'var(--badge-archive-outlined-label)',
	BADGE_HIGHLIGHT_DANGER_OUTLINED_BACKGROUND:
		'var(--badge-highlight-danger-outlined-background)',
	BADGE_HIGHLIGHT_DANGER_OUTLINED_BORDER:
		'var(--badge-highlight-danger-outlined-border)',
	BADGE_HIGHLIGHT_DANGER_OUTLINED_LABEL:
		'var(--badge-highlight-danger-outlined-label)',
	RADIO_GROUP_BORDER: 'var(--radio-group-border)',
	RADIO_GROUP_LABEL: 'var(--radio-group-label)',
	RADIO_GROUP_LABEL_HOVER: 'var(--radio-group-label-hover)',
	RADIO_GROUP_PRIMARY_BACKGROUND: 'var(--radio-group-primary-background)',
	RADIO_GROUP_PRIMARY_BORDER_HOVER: 'var(--radio-group-primary-border-hover)',
	RADIO_GROUP_PRIMARY_DOT: 'var(--radio-group-primary-dot)',
	RADIO_GROUP_SECONDARY_BACKGROUND: 'var(--radio-group-secondary-background)',
	RADIO_GROUP_SECONDARY_BORDER_HOVER:
		'var(--radio-group-secondary-border-hover)',
	RADIO_GROUP_SECONDARY_DOT: 'var(--radio-group-secondary-dot)',
	RADIO_GROUP_SUCCESS_BACKGROUND: 'var(--radio-group-success-background)',
	RADIO_GROUP_SUCCESS_BORDER_HOVER: 'var(--radio-group-success-border-hover)',
	RADIO_GROUP_SUCCESS_DOT: 'var(--radio-group-success-dot)',
	RADIO_GROUP_WARNING_BACKGROUND: 'var(--radio-group-warning-background)',
	RADIO_GROUP_WARNING_BORDER_HOVER: 'var(--radio-group-warning-border-hover)',
	RADIO_GROUP_WARNING_DOT: 'var(--radio-group-warning-dot)',
	RADIO_GROUP_DANGER_BACKGROUND: 'var(--radio-group-danger-background)',
	RADIO_GROUP_DANGER_BORDER_HOVER: 'var(--radio-group-danger-border-hover)',
	RADIO_GROUP_DANGER_DOT: 'var(--radio-group-danger-dot)',
	RADIO_GROUP_INFO_BACKGROUND: 'var(--radio-group-info-background)',
	RADIO_GROUP_INFO_BORDER_HOVER: 'var(--radio-group-info-border-hover)',
	RADIO_GROUP_INFO_DOT: 'var(--radio-group-info-dot)',
	RADIO_GROUP_ARCHIVE_BACKGROUND: 'var(--radio-group-archive-background)',
	RADIO_GROUP_ARCHIVE_BORDER_HOVER: 'var(--radio-group-archive-border-hover)',
	RADIO_GROUP_ARCHIVE_DOT: 'var(--radio-group-archive-dot)',
	RADIO_GROUP_HIGHLIGHT_DANGER_BACKGROUND:
		'var(--radio-group-highlight-danger-background)',
	RADIO_GROUP_HIGHLIGHT_DANGER_BORDER_HOVER:
		'var(--radio-group-highlight-danger-border-hover)',
	RADIO_GROUP_HIGHLIGHT_DANGER_DOT: 'var(--radio-group-highlight-danger-dot)',
	RADIO_GROUP_FOCUS_RING: 'var(--radio-group-focus-ring)',
	SWITCH_TRACK_BACKGROUND: 'var(--switch-track-background)',
	SWITCH_TRACK_HOVER_BACKGROUND: 'var(--switch-track-hover-background)',
	SWITCH_PRIMARY_BACKGROUND: 'var(--switch-primary-background)',
	SWITCH_PRIMARY_HOVER_BACKGROUND: 'var(--switch-primary-hover-background)',
	SWITCH_SECONDARY_BACKGROUND: 'var(--switch-secondary-background)',
	SWITCH_SECONDARY_HOVER_BACKGROUND: 'var(--switch-secondary-hover-background)',
	SWITCH_SUCCESS_BACKGROUND: 'var(--switch-success-background)',
	SWITCH_SUCCESS_HOVER_BACKGROUND: 'var(--switch-success-hover-background)',
	SWITCH_WARNING_BACKGROUND: 'var(--switch-warning-background)',
	SWITCH_WARNING_HOVER_BACKGROUND: 'var(--switch-warning-hover-background)',
	SWITCH_DANGER_BACKGROUND: 'var(--switch-danger-background)',
	SWITCH_DANGER_HOVER_BACKGROUND: 'var(--switch-danger-hover-background)',
	SWITCH_INFO_BACKGROUND: 'var(--switch-info-background)',
	SWITCH_INFO_HOVER_BACKGROUND: 'var(--switch-info-hover-background)',
	SWITCH_ARCHIVE_BACKGROUND: 'var(--switch-archive-background)',
	SWITCH_ARCHIVE_HOVER_BACKGROUND: 'var(--switch-archive-hover-background)',
	SWITCH_HIGHLIGHT_DANGER_BACKGROUND:
		'var(--switch-highlight-danger-background)',
	SWITCH_HIGHLIGHT_DANGER_HOVER_BACKGROUND:
		'var(--switch-highlight-danger-hover-background)',
	SWITCH_THUMB_BACKGROUND: 'var(--switch-thumb-background)',
	SWITCH_LABEL: 'var(--switch-label)',
	SWITCH_DESCRIPTION: 'var(--switch-description)',
	SWITCH_FOCUS_RING: 'var(--switch-focus-ring)',
	TABS_BORDER: 'var(--tabs-border)',
	TABS_PRIMARY_LABEL: 'var(--tabs-primary-label)',
	TABS_PRIMARY_LABEL_HOVER: 'var(--tabs-primary-label-hover)',
	TABS_PRIMARY_BACKGROUND_HOVER: 'var(--tabs-primary-background-hover)',
	TABS_PRIMARY_INDICATOR: 'var(--tabs-primary-indicator)',
	TABS_PRIMARY_RADIUS: 'var(--tabs-primary-radius)',
	TABS_SECONDARY_BACKGROUND: 'var(--tabs-secondary-background)',
	TABS_SECONDARY_BACKGROUND_HOVER: 'var(--tabs-secondary-background-hover)',
	TABS_SECONDARY_LABEL: 'var(--tabs-secondary-label)',
	TABS_SECONDARY_LABEL_HOVER: 'var(--tabs-secondary-label-hover)',
	TABS_SECONDARY_LABEL_ACTIVE: 'var(--tabs-secondary-label-active)',
	TABS_SECONDARY_LABEL_DISABLED: 'var(--tabs-secondary-label-disabled)',
	TABS_SECONDARY_STRIPE_DISABLED: 'var(--tabs-secondary-stripe-disabled)',
	TABS_LABEL: 'var(--tabs-label)',
	TABS_LABEL_HOVER: 'var(--tabs-label-hover)',
	TABS_HOVER_SLIDER_BACKGROUND: 'var(--tabs-hover-slider-background)',
	TABS_FOCUS_RING: 'var(--tabs-focus-ring)',
	TABS_FOCUS_RING_OFFSET: 'var(--tabs-focus-ring-offset)',
	TOGGLE_GROUP_BORDER: 'var(--toggle-group-border)',
	TOGGLE_GROUP_SECONDARY_OUTLINED_BACKGROUND:
		'var(--toggle-group-secondary-outlined-background)',
	TOGGLE_GROUP_SECONDARY_OUTLINED_BACKGROUND_HOVER:
		'var(--toggle-group-secondary-outlined-background-hover)',
	TOGGLE_GROUP_SECONDARY_OUTLINED_BACKGROUND_ACTIVE:
		'var(--toggle-group-secondary-outlined-background-active)',
	TOGGLE_GROUP_SECONDARY_OUTLINED_LABEL:
		'var(--toggle-group-secondary-outlined-label)',
	TOGGLE_GROUP_SECONDARY_OUTLINED_LABEL_HOVER:
		'var(--toggle-group-secondary-outlined-label-hover)',
	TOGGLE_GROUP_SECONDARY_OUTLINED_LABEL_ACTIVE:
		'var(--toggle-group-secondary-outlined-label-active)',
	TOGGLE_GROUP_SECONDARY_OUTLINED_LABEL_DISABLED:
		'var(--toggle-group-secondary-outlined-label-disabled)',
	TOGGLE_GROUP_SCROLL_BUTTON_BACKGROUND:
		'var(--toggle-group-scroll-button-background)',
	TOGGLE_GROUP_SCROLL_BUTTON_BACKGROUND_HOVER:
		'var(--toggle-group-scroll-button-background-hover)',
	TOGGLE_GROUP_SCROLL_BUTTON_LABEL: 'var(--toggle-group-scroll-button-label)',
	TOGGLE_GROUP_SCROLL_BUTTON_LABEL_HOVER:
		'var(--toggle-group-scroll-button-label-hover)',
	TOGGLE_GROUP_SCROLL_BUTTON_SHADOW_COLOR:
		'var(--toggle-group-scroll-button-shadow-color)',
	TOGGLE_GROUP_FOCUS_RING: 'var(--toggle-group-focus-ring)',
	DROPDOWN_BACKGROUND: 'var(--dropdown-background)',
	DROPDOWN_BORDER: 'var(--dropdown-border)',
	DROPDOWN_SHADOW: 'var(--dropdown-shadow)',
	DROPDOWN_ITEM_LABEL: 'var(--dropdown-item-label)',
	DROPDOWN_ITEM_LABEL_HOVER: 'var(--dropdown-item-label-hover)',
	DROPDOWN_ITEM_LABEL_DISABLED: 'var(--dropdown-item-label-disabled)',
	DROPDOWN_ITEM_BACKGROUND: 'var(--dropdown-item-background)',
	DROPDOWN_ITEM_BACKGROUND_HOVER: 'var(--dropdown-item-background-hover)',
	DROPDOWN_ITEM_DANGER_LABEL: 'var(--dropdown-item-danger-label)',
	DROPDOWN_ITEM_DANGER_LABEL_HOVER: 'var(--dropdown-item-danger-label-hover)',
	DROPDOWN_ITEM_DANGER_BACKGROUND_HOVER:
		'var(--dropdown-item-danger-background-hover)',
	DROPDOWN_ITEM_ICON: 'var(--dropdown-item-icon)',
	DROPDOWN_ITEM_ICON_HOVER: 'var(--dropdown-item-icon-hover)',
	DROPDOWN_GROUP_LABEL: 'var(--dropdown-group-label)',
	DROPDOWN_SEPARATOR: 'var(--dropdown-separator)',
	DROPDOWN_SEARCH_PLACEHOLDER: 'var(--dropdown-search-placeholder)',
	DROPDOWN_SEARCH_ICON: 'var(--dropdown-search-icon)',
	DROPDOWN_SEARCH_BORDER: 'var(--dropdown-search-border)',
	DROPDOWN_LOADING_LABEL: 'var(--dropdown-loading-label)',
	DROPDOWN_ITEM_FOCUS_RING: 'var(--dropdown-item-focus-ring)',
	DROPDOWN_SCROLL_FADE: 'var(--dropdown-scroll-fade)',
	CALENDAR_BACKGROUND: 'var(--calendar-background)',
	CALENDAR_BUTTON_BACKGROUND: 'var(--calendar-button-background)',
	CALENDAR_BUTTON_BACKGROUND_HOVER: 'var(--calendar-button-background-hover)',
	CALENDAR_BUTTON_BACKGROUND_ACTIVE: 'var(--calendar-button-background-active)',
	CALENDAR_BUTTON_LABEL: 'var(--calendar-button-label)',
	CALENDAR_BUTTON_LABEL_HOVER: 'var(--calendar-button-label-hover)',
	CALENDAR_BUTTON_FOCUS_RING: 'var(--calendar-button-focus-ring)',
	CALENDAR_DAY_SELECTED_BACKGROUND: 'var(--calendar-day-selected-background)',
	CALENDAR_DAY_SELECTED_BACKGROUND_HOVER:
		'var(--calendar-day-selected-background-hover)',
	CALENDAR_DAY_SELECTED_LABEL: 'var(--calendar-day-selected-label)',
	CALENDAR_DAY_RANGE_EDGE_BACKGROUND:
		'var(--calendar-day-range-edge-background)',
	CALENDAR_DAY_RANGE_EDGE_BACKGROUND_HOVER:
		'var(--calendar-day-range-edge-background-hover)',
	CALENDAR_DAY_RANGE_EDGE_LABEL: 'var(--calendar-day-range-edge-label)',
	CALENDAR_DAY_RANGE_MIDDLE_BACKGROUND:
		'var(--calendar-day-range-middle-background)',
	CALENDAR_DAY_RANGE_MIDDLE_BACKGROUND_HOVER:
		'var(--calendar-day-range-middle-background-hover)',
	CALENDAR_DAY_RANGE_MIDDLE_LABEL: 'var(--calendar-day-range-middle-label)',
	CALENDAR_DAY_TODAY_BACKGROUND: 'var(--calendar-day-today-background)',
	CALENDAR_DAY_TODAY_LABEL: 'var(--calendar-day-today-label)',
	CALENDAR_DAY_OUTSIDE_LABEL: 'var(--calendar-day-outside-label)',
	CALENDAR_DAY_DISABLED_LABEL: 'var(--calendar-day-disabled-label)',
	CALENDAR_WEEKDAY_LABEL: 'var(--calendar-weekday-label)',
	CALENDAR_WEEK_NUMBER_LABEL: 'var(--calendar-week-number-label)',
	CALENDAR_SELECT_BACKGROUND: 'var(--calendar-select-background)',
	CALENDAR_SELECT_BORDER: 'var(--calendar-select-border)',
	CALENDAR_SELECT_BORDER_FOCUS: 'var(--calendar-select-border-focus)',
	CALENDAR_SELECT_ICON: 'var(--calendar-select-icon)',
	CALENDAR_SELECT_SHADOW: 'var(--calendar-select-shadow)',
	CALENDAR_SELECT_SHADOW_FOCUS: 'var(--calendar-select-shadow-focus)',
	BUTTON_GROUP_SECONDARY_OUTLINED_BACKGROUND:
		'var(--button-group-secondary-outlined-background)',
	BUTTON_GROUP_SECONDARY_OUTLINED_BACKGROUND_HOVER:
		'var(--button-group-secondary-outlined-background-hover)',
	BUTTON_GROUP_SECONDARY_OUTLINED_LABEL:
		'var(--button-group-secondary-outlined-label)',
	BUTTON_GROUP_SECONDARY_OUTLINED_LABEL_HOVER:
		'var(--button-group-secondary-outlined-label-hover)',
	BUTTON_GROUP_SECONDARY_OUTLINED_BORDER:
		'var(--button-group-secondary-outlined-border)',
	BUTTON_GROUP_SECONDARY_OUTLINED_DISABLED_STRIPE:
		'var(--button-group-secondary-outlined-disabled-stripe)',
	BUTTON_GROUP_FOCUS_RING: 'var(--button-group-focus-ring)',
	CHECKBOX_BORDER: 'var(--checkbox-border)',
	CHECKBOX_LABEL: 'var(--checkbox-label)',
	CHECKBOX_PRIMARY_BACKGROUND: 'var(--checkbox-primary-background)',
	CHECKBOX_PRIMARY_FOREGROUND: 'var(--checkbox-primary-foreground)',
	CHECKBOX_PRIMARY_BORDER_HOVER: 'var(--checkbox-primary-border-hover)',
	CHECKBOX_SECONDARY_BACKGROUND: 'var(--checkbox-secondary-background)',
	CHECKBOX_SECONDARY_FOREGROUND: 'var(--checkbox-secondary-foreground)',
	CHECKBOX_SECONDARY_BORDER_HOVER: 'var(--checkbox-secondary-border-hover)',
	CHECKBOX_SUCCESS_BACKGROUND: 'var(--checkbox-success-background)',
	CHECKBOX_SUCCESS_FOREGROUND: 'var(--checkbox-success-foreground)',
	CHECKBOX_SUCCESS_BORDER_HOVER: 'var(--checkbox-success-border-hover)',
	CHECKBOX_WARNING_BACKGROUND: 'var(--checkbox-warning-background)',
	CHECKBOX_WARNING_FOREGROUND: 'var(--checkbox-warning-foreground)',
	CHECKBOX_WARNING_BORDER_HOVER: 'var(--checkbox-warning-border-hover)',
	CHECKBOX_DANGER_BACKGROUND: 'var(--checkbox-danger-background)',
	CHECKBOX_DANGER_FOREGROUND: 'var(--checkbox-danger-foreground)',
	CHECKBOX_DANGER_BORDER_HOVER: 'var(--checkbox-danger-border-hover)',
	CHECKBOX_INFO_BACKGROUND: 'var(--checkbox-info-background)',
	CHECKBOX_INFO_FOREGROUND: 'var(--checkbox-info-foreground)',
	CHECKBOX_INFO_BORDER_HOVER: 'var(--checkbox-info-border-hover)',
	CHECKBOX_ARCHIVE_BACKGROUND: 'var(--checkbox-archive-background)',
	CHECKBOX_ARCHIVE_FOREGROUND: 'var(--checkbox-archive-foreground)',
	CHECKBOX_ARCHIVE_BORDER_HOVER: 'var(--checkbox-archive-border-hover)',
	CHECKBOX_HIGHLIGHT_DANGER_BACKGROUND:
		'var(--checkbox-highlight-danger-background)',
	CHECKBOX_HIGHLIGHT_DANGER_FOREGROUND:
		'var(--checkbox-highlight-danger-foreground)',
	CHECKBOX_HIGHLIGHT_DANGER_BORDER_HOVER:
		'var(--checkbox-highlight-danger-border-hover)',
	CHECKBOX_FOCUS_RING: 'var(--checkbox-focus-ring)',
} as const;

export type StyleType = typeof Style;
