/**
 * Semantic Token Tailwind Config
 * DO NOT EDIT DIRECTLY - This file is auto-generated
 * Generated on Thu, 24 Sep 2026 14:58:50 GMT
 */

export const StyleTailwind = {
	background: 'var(--background)',
	foreground: 'var(--foreground)',
	card: 'var(--card)',
	'card-foreground': 'var(--card-foreground)',
	popover: 'var(--popover)',
	'popover-foreground': 'var(--popover-foreground)',
	primary: 'var(--primary)',
	secondary: 'var(--secondary)',
	muted: 'var(--muted)',
	'muted-foreground': 'var(--muted-foreground)',
	accent: 'var(--accent)',
	'accent-foreground': 'var(--accent-foreground)',
	destructive: 'var(--destructive)',
	'destructive-foreground': 'var(--destructive-foreground)',
	border: 'var(--border)',
	input: 'var(--input)',
	ring: 'var(--ring)',
	radius: 'var(--radius)',
	'chart-1': 'var(--chart-1)',
	'chart-2': 'var(--chart-2)',
	'chart-3': 'var(--chart-3)',
	'chart-4': 'var(--chart-4)',
	'chart-5': 'var(--chart-5)',
	sidebar: 'var(--sidebar)',
	'sidebar-foreground': 'var(--sidebar-foreground)',
	'sidebar-primary': 'var(--sidebar-primary)',
	'sidebar-primary-foreground': 'var(--sidebar-primary-foreground)',
	'sidebar-accent': 'var(--sidebar-accent)',
	'sidebar-accent-foreground': 'var(--sidebar-accent-foreground)',
	'sidebar-border': 'var(--sidebar-border)',
	'sidebar-ring': 'var(--sidebar-ring)',
	'font-sans': 'var(--font-sans)',
	'font-serif': 'var(--font-serif)',
	'font-mono': 'var(--font-mono)',
	'base-white': 'var(--base-white)',
	'base-black': 'var(--base-black)',
	'l1-background': 'var(--l1-background)',
	'l2-background': 'var(--l2-background)',
	'l3-background': 'var(--l3-background)',
	'l1-background-hover': 'var(--l1-background-hover)',
	'l2-background-hover': 'var(--l2-background-hover)',
	'l3-background-hover': 'var(--l3-background-hover)',
	'l1-foreground': 'var(--l1-foreground)',
	'l1-foreground-hover': 'var(--l1-foreground-hover)',
	'l2-foreground': 'var(--l2-foreground)',
	'l2-foreground-hover': 'var(--l2-foreground-hover)',
	'l3-foreground': 'var(--l3-foreground)',
	'l3-foreground-hover': 'var(--l3-foreground-hover)',
	'l1-border': 'var(--l1-border)',
	'l2-border': 'var(--l2-border)',
	'l3-border': 'var(--l3-border)',
	'primary-background': 'var(--primary-background)',
	'primary-background-hover': 'var(--primary-background-hover)',
	'primary-foreground': 'var(--primary-foreground)',
	'primary-foreground-hover': 'var(--primary-foreground-hover)',
	'secondary-background': 'var(--secondary-background)',
	'secondary-background-hover': 'var(--secondary-background-hover)',
	'secondary-foreground': 'var(--secondary-foreground)',
	'secondary-foreground-hover': 'var(--secondary-foreground-hover)',
	'secondary-border': 'var(--secondary-border)',
	'success-background': 'var(--success-background)',
	'success-background-hover': 'var(--success-background-hover)',
	'success-foreground': 'var(--success-foreground)',
	'success-foreground-hover': 'var(--success-foreground-hover)',
	'warning-background': 'var(--warning-background)',
	'warning-background-hover': 'var(--warning-background-hover)',
	'warning-foreground': 'var(--warning-foreground)',
	'warning-foreground-hover': 'var(--warning-foreground-hover)',
	'danger-background': 'var(--danger-background)',
	'danger-background-hover': 'var(--danger-background-hover)',
	'danger-foreground': 'var(--danger-foreground)',
	'danger-foreground-hover': 'var(--danger-foreground-hover)',
	'primary-link': 'var(--primary-link)',
	'primary-link-hover': 'var(--primary-link-hover)',
	'secondary-link': 'var(--secondary-link)',
	'secondary-link-hover': 'var(--secondary-link-hover)',
	'success-link': 'var(--success-link)',
	'success-link-hover': 'var(--success-link-hover)',
	'warning-link': 'var(--warning-link)',
	'warning-link-hover': 'var(--warning-link-hover)',
	'danger-link': 'var(--danger-link)',
	'danger-link-hover': 'var(--danger-link-hover)',
	'l1-background-transparent': 'var(--l1-background-transparent)',
	'l1-background-60': 'var(--l1-background-60)',
	'l2-background-transparent': 'var(--l2-background-transparent)',
	'l2-background-60': 'var(--l2-background-60)',
	'l3-background-transparent': 'var(--l3-background-transparent)',
	'l3-background-60': 'var(--l3-background-60)',
	'l3-background-30': 'var(--l3-background-30)',
	'surface-1': 'var(--surface-1)',
	'surface-2': 'var(--surface-2)',
	'surface-3': 'var(--surface-3)',
	'surface-static': 'var(--surface-static)',
	'alert-strip-button-background': 'var(--alert-strip-button-background)',
	'callout-primary-background': 'var(--callout-primary-background)',
	'callout-primary-border': 'var(--callout-primary-border)',
	'callout-primary-title': 'var(--callout-primary-title)',
	'callout-primary-description': 'var(--callout-primary-description)',
	'callout-primary-icon': 'var(--callout-primary-icon)',
	'callout-success-background': 'var(--callout-success-background)',
	'callout-success-border': 'var(--callout-success-border)',
	'callout-success-title': 'var(--callout-success-title)',
	'callout-success-description': 'var(--callout-success-description)',
	'callout-success-icon': 'var(--callout-success-icon)',
	'callout-warning-background': 'var(--callout-warning-background)',
	'callout-warning-border': 'var(--callout-warning-border)',
	'callout-warning-title': 'var(--callout-warning-title)',
	'callout-warning-description': 'var(--callout-warning-description)',
	'callout-warning-icon': 'var(--callout-warning-icon)',
	'callout-error-background': 'var(--callout-error-background)',
	'callout-error-border': 'var(--callout-error-border)',
	'callout-error-title': 'var(--callout-error-title)',
	'callout-error-description': 'var(--callout-error-description)',
	'callout-error-icon': 'var(--callout-error-icon)',
	'accent-primary': 'var(--accent-primary)',
	'accent-primary-hover': 'var(--accent-primary-hover)',
	'accent-primary-foreground': 'var(--accent-primary-foreground)',
	'accent-forest': 'var(--accent-forest)',
	'accent-forest-hover': 'var(--accent-forest-hover)',
	'accent-forest-foreground': 'var(--accent-forest-foreground)',
	'accent-amber': 'var(--accent-amber)',
	'accent-amber-hover': 'var(--accent-amber-hover)',
	'accent-amber-foreground': 'var(--accent-amber-foreground)',
	'accent-cherry': 'var(--accent-cherry)',
	'accent-cherry-hover': 'var(--accent-cherry-hover)',
	'accent-cherry-foreground': 'var(--accent-cherry-foreground)',
	'accent-aqua': 'var(--accent-aqua)',
	'accent-aqua-hover': 'var(--accent-aqua-hover)',
	'accent-aqua-foreground': 'var(--accent-aqua-foreground)',
	'accent-sakura': 'var(--accent-sakura)',
	'accent-sakura-hover': 'var(--accent-sakura-hover)',
	'accent-sakura-foreground': 'var(--accent-sakura-foreground)',
	'accent-sienna': 'var(--accent-sienna)',
	'accent-sienna-hover': 'var(--accent-sienna-hover)',
	'accent-sienna-foreground': 'var(--accent-sienna-foreground)',
	'ghost-background': 'var(--ghost-background)',
	'ghost-background-hover': 'var(--ghost-background-hover)',
	'ghost-foreground': 'var(--ghost-foreground)',
	'ghost-foreground-hover': 'var(--ghost-foreground-hover)',
	'ghost-border': 'var(--ghost-border)',
	'action-background': 'var(--action-background)',
	'action-background-hover': 'var(--action-background-hover)',
	'action-border': 'var(--action-border)',
	'action-border-hover': 'var(--action-border-hover)',
	'action-foreground': 'var(--action-foreground)',
	'action-foreground-hover': 'var(--action-foreground-hover)',
	'callout-sienna-background': 'var(--callout-sienna-background)',
	'callout-sienna-border': 'var(--callout-sienna-border)',
	'callout-sienna-title': 'var(--callout-sienna-title)',
	'callout-sienna-description': 'var(--callout-sienna-description)',
	'callout-sienna-icon': 'var(--callout-sienna-icon)',
	'callout-aqua-background': 'var(--callout-aqua-background)',
	'callout-aqua-border': 'var(--callout-aqua-border)',
	'callout-aqua-title': 'var(--callout-aqua-title)',
	'callout-aqua-description': 'var(--callout-aqua-description)',
	'callout-aqua-icon': 'var(--callout-aqua-icon)',
	'control-icon-foreground': 'var(--control-icon-foreground)',
	'control-icon-foreground-contrast': 'var(--control-icon-foreground-contrast)',
	'shadow-sidebar': 'var(--shadow-sidebar)',
	'shadow-dropdown': 'var(--shadow-dropdown)',
	'shadow-drawer': 'var(--shadow-drawer)',
	'shadow-dialog': 'var(--shadow-dialog)',
	'shadow-toast': 'var(--shadow-toast)',
	'shadow-tooltip': 'var(--shadow-tooltip)',
	'pill-primary-background': 'var(--pill-primary-background)',
	'pill-primary-border': 'var(--pill-primary-border)',
	'pill-primary-label': 'var(--pill-primary-label)',
	'pill-primary-label-hover': 'var(--pill-primary-label-hover)',
	'pill-success-background': 'var(--pill-success-background)',
	'pill-success-border': 'var(--pill-success-border)',
	'pill-success-label': 'var(--pill-success-label)',
	'pill-success-label-hover': 'var(--pill-success-label-hover)',
	'pill-warning-background': 'var(--pill-warning-background)',
	'pill-warning-border': 'var(--pill-warning-border)',
	'pill-warning-label': 'var(--pill-warning-label)',
	'pill-warning-label-hover': 'var(--pill-warning-label-hover)',
	'pill-danger-background': 'var(--pill-danger-background)',
	'pill-danger-border': 'var(--pill-danger-border)',
	'pill-danger-label': 'var(--pill-danger-label)',
	'pill-danger-label-hover': 'var(--pill-danger-label-hover)',
	'pill-outlined-background': 'var(--pill-outlined-background)',
	'pill-outlined-background-hover': 'var(--pill-outlined-background-hover)',
	'pill-outlined-border': 'var(--pill-outlined-border)',
	'pill-outlined-label': 'var(--pill-outlined-label)',
	'pill-outlined-label-hover': 'var(--pill-outlined-label-hover)',
	'pill-rect-solid-background': 'var(--pill-rect-solid-background)',
	'pill-rect-solid-background-hover': 'var(--pill-rect-solid-background-hover)',
	'pill-rect-solid-label': 'var(--pill-rect-solid-label)',
	'pill-rect-solid-label-hover': 'var(--pill-rect-solid-label-hover)',
	'pill-rect-solid-dismiss-icon': 'var(--pill-rect-solid-dismiss-icon)',
	'pill-rect-solid-dismiss-icon-hover':
		'var(--pill-rect-solid-dismiss-icon-hover)',
	'pill-info-background': 'var(--pill-info-background)',
	'pill-info-border': 'var(--pill-info-border)',
	'pill-info-label': 'var(--pill-info-label)',
	'pill-info-label-hover': 'var(--pill-info-label-hover)',
	'pill-archive-background': 'var(--pill-archive-background)',
	'pill-archive-border': 'var(--pill-archive-border)',
	'pill-archive-label': 'var(--pill-archive-label)',
	'pill-archive-label-hover': 'var(--pill-archive-label-hover)',
	'pill-highlight-danger-background': 'var(--pill-highlight-danger-background)',
	'pill-highlight-danger-border': 'var(--pill-highlight-danger-border)',
	'pill-highlight-danger-label': 'var(--pill-highlight-danger-label)',
	'pill-highlight-danger-label-hover':
		'var(--pill-highlight-danger-label-hover)',
	'pill-invalid-border': 'var(--pill-invalid-border)',
	'pill-invalid-label': 'var(--pill-invalid-label)',
	'pill-focus-ring': 'var(--pill-focus-ring)',
	'badge-primary-outlined-background':
		'var(--badge-primary-outlined-background)',
	'badge-primary-outlined-border': 'var(--badge-primary-outlined-border)',
	'badge-primary-outlined-label': 'var(--badge-primary-outlined-label)',
	'badge-primary-outlined-icon': 'var(--badge-primary-outlined-icon)',
	'badge-success-outlined-background':
		'var(--badge-success-outlined-background)',
	'badge-success-outlined-border': 'var(--badge-success-outlined-border)',
	'badge-success-outlined-label': 'var(--badge-success-outlined-label)',
	'badge-success-outlined-icon': 'var(--badge-success-outlined-icon)',
	'badge-warning-outlined-background':
		'var(--badge-warning-outlined-background)',
	'badge-warning-outlined-border': 'var(--badge-warning-outlined-border)',
	'badge-warning-outlined-label': 'var(--badge-warning-outlined-label)',
	'badge-warning-outlined-icon': 'var(--badge-warning-outlined-icon)',
	'badge-danger-outlined-background': 'var(--badge-danger-outlined-background)',
	'badge-danger-outlined-border': 'var(--badge-danger-outlined-border)',
	'badge-danger-outlined-label': 'var(--badge-danger-outlined-label)',
	'badge-danger-outlined-icon': 'var(--badge-danger-outlined-icon)',
	'badge-secondary-outlined-background':
		'var(--badge-secondary-outlined-background)',
	'badge-secondary-outlined-border': 'var(--badge-secondary-outlined-border)',
	'badge-secondary-outlined-label': 'var(--badge-secondary-outlined-label)',
	'badge-secondary-outlined-icon': 'var(--badge-secondary-outlined-icon)',
	'badge-primary-background': 'var(--badge-primary-background)',
	'badge-primary-foreground': 'var(--badge-primary-foreground)',
	'badge-secondary-background': 'var(--badge-secondary-background)',
	'badge-secondary-foreground': 'var(--badge-secondary-foreground)',
	'badge-success-background': 'var(--badge-success-background)',
	'badge-success-foreground': 'var(--badge-success-foreground)',
	'badge-warning-background': 'var(--badge-warning-background)',
	'badge-warning-foreground': 'var(--badge-warning-foreground)',
	'badge-danger-background': 'var(--badge-danger-background)',
	'badge-danger-foreground': 'var(--badge-danger-foreground)',
	'badge-info-background': 'var(--badge-info-background)',
	'badge-info-foreground': 'var(--badge-info-foreground)',
	'badge-archive-background': 'var(--badge-archive-background)',
	'badge-archive-foreground': 'var(--badge-archive-foreground)',
	'badge-highlight-danger-background':
		'var(--badge-highlight-danger-background)',
	'badge-highlight-danger-foreground':
		'var(--badge-highlight-danger-foreground)',
	'badge-secondary-border': 'var(--badge-secondary-border)',
	'badge-info-outlined-background': 'var(--badge-info-outlined-background)',
	'badge-info-outlined-border': 'var(--badge-info-outlined-border)',
	'badge-info-outlined-label': 'var(--badge-info-outlined-label)',
	'badge-archive-outlined-background':
		'var(--badge-archive-outlined-background)',
	'badge-archive-outlined-border': 'var(--badge-archive-outlined-border)',
	'badge-archive-outlined-label': 'var(--badge-archive-outlined-label)',
	'badge-highlight-danger-outlined-background':
		'var(--badge-highlight-danger-outlined-background)',
	'badge-highlight-danger-outlined-border':
		'var(--badge-highlight-danger-outlined-border)',
	'badge-highlight-danger-outlined-label':
		'var(--badge-highlight-danger-outlined-label)',
	'radio-group-border': 'var(--radio-group-border)',
	'radio-group-label': 'var(--radio-group-label)',
	'radio-group-label-hover': 'var(--radio-group-label-hover)',
	'radio-group-primary-background': 'var(--radio-group-primary-background)',
	'radio-group-primary-border-hover': 'var(--radio-group-primary-border-hover)',
	'radio-group-primary-dot': 'var(--radio-group-primary-dot)',
	'radio-group-secondary-background': 'var(--radio-group-secondary-background)',
	'radio-group-secondary-border-hover':
		'var(--radio-group-secondary-border-hover)',
	'radio-group-secondary-dot': 'var(--radio-group-secondary-dot)',
	'radio-group-success-background': 'var(--radio-group-success-background)',
	'radio-group-success-border-hover': 'var(--radio-group-success-border-hover)',
	'radio-group-success-dot': 'var(--radio-group-success-dot)',
	'radio-group-warning-background': 'var(--radio-group-warning-background)',
	'radio-group-warning-border-hover': 'var(--radio-group-warning-border-hover)',
	'radio-group-warning-dot': 'var(--radio-group-warning-dot)',
	'radio-group-danger-background': 'var(--radio-group-danger-background)',
	'radio-group-danger-border-hover': 'var(--radio-group-danger-border-hover)',
	'radio-group-danger-dot': 'var(--radio-group-danger-dot)',
	'radio-group-info-background': 'var(--radio-group-info-background)',
	'radio-group-info-border-hover': 'var(--radio-group-info-border-hover)',
	'radio-group-info-dot': 'var(--radio-group-info-dot)',
	'radio-group-archive-background': 'var(--radio-group-archive-background)',
	'radio-group-archive-border-hover': 'var(--radio-group-archive-border-hover)',
	'radio-group-archive-dot': 'var(--radio-group-archive-dot)',
	'radio-group-highlight-danger-background':
		'var(--radio-group-highlight-danger-background)',
	'radio-group-highlight-danger-border-hover':
		'var(--radio-group-highlight-danger-border-hover)',
	'radio-group-highlight-danger-dot': 'var(--radio-group-highlight-danger-dot)',
	'radio-group-focus-ring': 'var(--radio-group-focus-ring)',
	'switch-track-background': 'var(--switch-track-background)',
	'switch-track-hover-background': 'var(--switch-track-hover-background)',
	'switch-primary-background': 'var(--switch-primary-background)',
	'switch-primary-hover-background': 'var(--switch-primary-hover-background)',
	'switch-secondary-background': 'var(--switch-secondary-background)',
	'switch-secondary-hover-background':
		'var(--switch-secondary-hover-background)',
	'switch-success-background': 'var(--switch-success-background)',
	'switch-success-hover-background': 'var(--switch-success-hover-background)',
	'switch-warning-background': 'var(--switch-warning-background)',
	'switch-warning-hover-background': 'var(--switch-warning-hover-background)',
	'switch-danger-background': 'var(--switch-danger-background)',
	'switch-danger-hover-background': 'var(--switch-danger-hover-background)',
	'switch-info-background': 'var(--switch-info-background)',
	'switch-info-hover-background': 'var(--switch-info-hover-background)',
	'switch-archive-background': 'var(--switch-archive-background)',
	'switch-archive-hover-background': 'var(--switch-archive-hover-background)',
	'switch-highlight-danger-background':
		'var(--switch-highlight-danger-background)',
	'switch-highlight-danger-hover-background':
		'var(--switch-highlight-danger-hover-background)',
	'switch-thumb-background': 'var(--switch-thumb-background)',
	'switch-label': 'var(--switch-label)',
	'switch-description': 'var(--switch-description)',
	'switch-focus-ring': 'var(--switch-focus-ring)',
	'tabs-border': 'var(--tabs-border)',
	'tabs-primary-label': 'var(--tabs-primary-label)',
	'tabs-primary-label-hover': 'var(--tabs-primary-label-hover)',
	'tabs-primary-background-hover': 'var(--tabs-primary-background-hover)',
	'tabs-primary-indicator': 'var(--tabs-primary-indicator)',
	'tabs-primary-radius': 'var(--tabs-primary-radius)',
	'tabs-secondary-background': 'var(--tabs-secondary-background)',
	'tabs-secondary-background-hover': 'var(--tabs-secondary-background-hover)',
	'tabs-secondary-label': 'var(--tabs-secondary-label)',
	'tabs-secondary-label-hover': 'var(--tabs-secondary-label-hover)',
	'tabs-secondary-label-active': 'var(--tabs-secondary-label-active)',
	'tabs-secondary-label-disabled': 'var(--tabs-secondary-label-disabled)',
	'tabs-secondary-stripe-disabled': 'var(--tabs-secondary-stripe-disabled)',
	'toggle-group-border': 'var(--toggle-group-border)',
	'toggle-group-secondary-outlined-background':
		'var(--toggle-group-secondary-outlined-background)',
	'toggle-group-secondary-outlined-background-hover':
		'var(--toggle-group-secondary-outlined-background-hover)',
	'toggle-group-secondary-outlined-background-active':
		'var(--toggle-group-secondary-outlined-background-active)',
	'toggle-group-secondary-outlined-label':
		'var(--toggle-group-secondary-outlined-label)',
	'toggle-group-secondary-outlined-label-hover':
		'var(--toggle-group-secondary-outlined-label-hover)',
	'toggle-group-secondary-outlined-label-active':
		'var(--toggle-group-secondary-outlined-label-active)',
	'toggle-group-secondary-outlined-label-disabled':
		'var(--toggle-group-secondary-outlined-label-disabled)',
	'toggle-group-scroll-button-background':
		'var(--toggle-group-scroll-button-background)',
	'toggle-group-scroll-button-background-hover':
		'var(--toggle-group-scroll-button-background-hover)',
	'toggle-group-scroll-button-label': 'var(--toggle-group-scroll-button-label)',
	'toggle-group-scroll-button-label-hover':
		'var(--toggle-group-scroll-button-label-hover)',
	'toggle-group-scroll-button-shadow-color':
		'var(--toggle-group-scroll-button-shadow-color)',
	'toggle-group-focus-ring': 'var(--toggle-group-focus-ring)',
	'dropdown-background': 'var(--dropdown-background)',
	'dropdown-border': 'var(--dropdown-border)',
	'dropdown-shadow': 'var(--dropdown-shadow)',
	'dropdown-item-label': 'var(--dropdown-item-label)',
	'dropdown-item-label-hover': 'var(--dropdown-item-label-hover)',
	'dropdown-item-label-disabled': 'var(--dropdown-item-label-disabled)',
	'dropdown-item-background': 'var(--dropdown-item-background)',
	'dropdown-item-background-hover': 'var(--dropdown-item-background-hover)',
	'dropdown-item-danger-label': 'var(--dropdown-item-danger-label)',
	'dropdown-item-danger-label-hover': 'var(--dropdown-item-danger-label-hover)',
	'dropdown-item-danger-background-hover':
		'var(--dropdown-item-danger-background-hover)',
	'dropdown-item-icon': 'var(--dropdown-item-icon)',
	'dropdown-item-icon-hover': 'var(--dropdown-item-icon-hover)',
	'dropdown-group-label': 'var(--dropdown-group-label)',
	'dropdown-separator': 'var(--dropdown-separator)',
	'dropdown-search-placeholder': 'var(--dropdown-search-placeholder)',
	'dropdown-search-icon': 'var(--dropdown-search-icon)',
	'dropdown-search-border': 'var(--dropdown-search-border)',
	'dropdown-loading-label': 'var(--dropdown-loading-label)',
	'dropdown-item-focus-ring': 'var(--dropdown-item-focus-ring)',
	'dropdown-scroll-fade': 'var(--dropdown-scroll-fade)',
	'calendar-background': 'var(--calendar-background)',
	'calendar-button-background': 'var(--calendar-button-background)',
	'calendar-button-background-hover': 'var(--calendar-button-background-hover)',
	'calendar-button-background-active':
		'var(--calendar-button-background-active)',
	'calendar-button-label': 'var(--calendar-button-label)',
	'calendar-button-label-hover': 'var(--calendar-button-label-hover)',
	'calendar-button-focus-ring': 'var(--calendar-button-focus-ring)',
	'calendar-day-selected-background': 'var(--calendar-day-selected-background)',
	'calendar-day-selected-background-hover':
		'var(--calendar-day-selected-background-hover)',
	'calendar-day-selected-label': 'var(--calendar-day-selected-label)',
	'calendar-day-range-edge-background':
		'var(--calendar-day-range-edge-background)',
	'calendar-day-range-edge-background-hover':
		'var(--calendar-day-range-edge-background-hover)',
	'calendar-day-range-edge-label': 'var(--calendar-day-range-edge-label)',
	'calendar-day-range-middle-background':
		'var(--calendar-day-range-middle-background)',
	'calendar-day-range-middle-background-hover':
		'var(--calendar-day-range-middle-background-hover)',
	'calendar-day-range-middle-label': 'var(--calendar-day-range-middle-label)',
	'calendar-day-today-background': 'var(--calendar-day-today-background)',
	'calendar-day-today-label': 'var(--calendar-day-today-label)',
	'calendar-day-outside-label': 'var(--calendar-day-outside-label)',
	'calendar-day-disabled-label': 'var(--calendar-day-disabled-label)',
	'calendar-weekday-label': 'var(--calendar-weekday-label)',
	'calendar-week-number-label': 'var(--calendar-week-number-label)',
	'calendar-select-background': 'var(--calendar-select-background)',
	'calendar-select-border': 'var(--calendar-select-border)',
	'calendar-select-border-focus': 'var(--calendar-select-border-focus)',
	'calendar-select-icon': 'var(--calendar-select-icon)',
	'calendar-select-shadow': 'var(--calendar-select-shadow)',
	'calendar-select-shadow-focus': 'var(--calendar-select-shadow-focus)',
	'button-group-secondary-outlined-background':
		'var(--button-group-secondary-outlined-background)',
	'button-group-secondary-outlined-background-hover':
		'var(--button-group-secondary-outlined-background-hover)',
	'button-group-secondary-outlined-label':
		'var(--button-group-secondary-outlined-label)',
	'button-group-secondary-outlined-label-hover':
		'var(--button-group-secondary-outlined-label-hover)',
	'button-group-secondary-outlined-border':
		'var(--button-group-secondary-outlined-border)',
	'button-group-secondary-outlined-disabled-stripe':
		'var(--button-group-secondary-outlined-disabled-stripe)',
	'button-group-focus-ring': 'var(--button-group-focus-ring)',
	'checkbox-border': 'var(--checkbox-border)',
	'checkbox-label': 'var(--checkbox-label)',
	'checkbox-primary-background': 'var(--checkbox-primary-background)',
	'checkbox-primary-foreground': 'var(--checkbox-primary-foreground)',
	'checkbox-primary-border-hover': 'var(--checkbox-primary-border-hover)',
	'checkbox-secondary-background': 'var(--checkbox-secondary-background)',
	'checkbox-secondary-foreground': 'var(--checkbox-secondary-foreground)',
	'checkbox-secondary-border-hover': 'var(--checkbox-secondary-border-hover)',
	'checkbox-success-background': 'var(--checkbox-success-background)',
	'checkbox-success-foreground': 'var(--checkbox-success-foreground)',
	'checkbox-success-border-hover': 'var(--checkbox-success-border-hover)',
	'checkbox-warning-background': 'var(--checkbox-warning-background)',
	'checkbox-warning-foreground': 'var(--checkbox-warning-foreground)',
	'checkbox-warning-border-hover': 'var(--checkbox-warning-border-hover)',
	'checkbox-danger-background': 'var(--checkbox-danger-background)',
	'checkbox-danger-foreground': 'var(--checkbox-danger-foreground)',
	'checkbox-danger-border-hover': 'var(--checkbox-danger-border-hover)',
	'checkbox-info-background': 'var(--checkbox-info-background)',
	'checkbox-info-foreground': 'var(--checkbox-info-foreground)',
	'checkbox-info-border-hover': 'var(--checkbox-info-border-hover)',
	'checkbox-archive-background': 'var(--checkbox-archive-background)',
	'checkbox-archive-foreground': 'var(--checkbox-archive-foreground)',
	'checkbox-archive-border-hover': 'var(--checkbox-archive-border-hover)',
	'checkbox-highlight-danger-background':
		'var(--checkbox-highlight-danger-background)',
	'checkbox-highlight-danger-foreground':
		'var(--checkbox-highlight-danger-foreground)',
	'checkbox-highlight-danger-border-hover':
		'var(--checkbox-highlight-danger-border-hover)',
} as const;

export type StyleTailwindType =
	(typeof StyleTailwind)[keyof typeof StyleTailwind];
