name: release

on:
  push:
    branches:
      - "design-tokens-initial-setup"

jobs:
  test:
    uses: signoz/primus.workflows/.github/workflows/js-release.yaml@js-release
    secrets: inherit
    with:
      PRIMUS_REF: git
